const Option = [
        {"kode_klasifikasi":"KP.00","uraian_informasi":"Penyusunan dan Penetapan Kebutuhan Aparatur Sipil Negara (ASN)"},
        {"kode_klasifikasi":"KP.00.01","uraian_informasi":"Analisis Beban Kerja, Laporan Perencanaan Kebutuhan Pegawai dan Analisis Kebutuhan yang meliputi ASN dan Pegawai Pemerintah dengan Perjanjian Kerja"},
        {"kode_klasifikasi":"KP.00.02","uraian_informasi":"Penetapan Kebutuhan Aparatur Sipil Negara (ASN)"},
        {"kode_klasifikasi":"KP.00.03","uraian_informasi":"Pedoman Pola Karir"},
        {"kode_klasifikasi":"KP.01","uraian_informasi":"Formasi Pegawai"},
        {"kode_klasifikasi":"KP.01.01","uraian_informasi":"Usulan Permintaan Pengadaan"},
        {"kode_klasifikasi":"KP.01.02","uraian_informasi":"Persetujuan Formasi"},
        {"kode_klasifikasi":"KP.01.03","uraian_informasi":"Penetapan Formasi ASN"},
        {"kode_klasifikasi":"KP.01.04","uraian_informasi":"Penetapan Formasi Khusus"},
        {"kode_klasifikasi":"KP.01.05","uraian_informasi":"Surat Keputusan Penetapan Formasi"},
        {"kode_klasifikasi":"KP.02","uraian_informasi":"Pengadaan Pegawai ASN"},
        {"kode_klasifikasi":"KP.02.01","uraian_informasi":"Proses Rekrutmen Pegawai"},
        {"kode_klasifikasi":"KP.02.01","uraian_informasi":"Pengumuman, seleksi administrasi, pemanggilan peserta tes, pelaksanaan ujian, keputusan hasil ujian, wawancara"},
        {"kode_klasifikasi":"KP.02.02","uraian_informasi":"Penetapan Pengumuman Kelulusan"},
        {"kode_klasifikasi":"KP.02.03","uraian_informasi":"Berkas Lamaran yang Tidak Diterima"},
        {"kode_klasifikasi":"KP.02.04","uraian_informasi":"Berkas Pegawai Pemerintah dengan Perjanjian Kerja (PPPK) dan Pegawai Pemerintah Non Pegawai Negeri"},
        {"kode_klasifikasi":"KP.02.05","uraian_informasi":"Berkas Pegawai Lolos Butuh"},
        {"kode_klasifikasi":"KP.02.06","uraian_informasi":"Proses Pengangkatan Pegawai"},
        {"kode_klasifikasi":"KP.02.06","uraian_informasi":"Berkas lamaran CASN, nota usul pengangkatan CASN dan ASN, Surat Keputusan Pengangkatan\/Penempatan CASN, surat pernyataan melaksanakan tugas CASN, Berita Acara Pengambilan Sumpah Janji CASN, Laporan Magang\/Habituasi CASN"},
        {"kode_klasifikasi":"KP.02.07","uraian_informasi":"Usulan Peninjauan dan Penyesuaian Masa Kerja"},
        {"kode_klasifikasi":"KP.03","uraian_informasi":"Standarisasi Jabatan"},
        {"kode_klasifikasi":"KP.03.01","uraian_informasi":"Analisis Jabatan"},
        {"kode_klasifikasi":"KP.03.01","uraian_informasi":"Pedoman Analisis Jabatan, Kertas Kerja Analisis Jabatan, Uraian Jabatan, Peta Jabatan, Spesifikasi Jabatan"},
        {"kode_klasifikasi":"KP.03.02","uraian_informasi":"Evaluasi Jabatan"},
        {"kode_klasifikasi":"KP.03.02","uraian_informasi":"Pedoman Evaluasi Jabatan, Kertas Kerja Evaluasi Jabatan, Bobot Nilai Jabatan, Kelas Jabatan"},
        {"kode_klasifikasi":"KP.04","uraian_informasi":"Bezzeting\/Persediaan Pegawai"},
        {"kode_klasifikasi":"KP.05","uraian_informasi":"Mutasi Pegawai"},
        {"kode_klasifikasi":"KP.05.01","uraian_informasi":"Usulan Kenaikan Pangkat\/Golongan\/Jabatan"},
        {"kode_klasifikasi":"KP.05.01","uraian_informasi":"Kenaikan Pangkat\/Golongan\/Jabatan bagi Pejabat Pimpinan Tinggi dan Pejabat Administrasi termasuk di dalamnya pelantikan"},
        {"kode_klasifikasi":"KP.05.02","uraian_informasi":"Pemberhentian Jabatan"},
        {"kode_klasifikasi":"KP.05.02","uraian_informasi":"Kegiatan pemberhentian jabatan bagi Pejabat Pimpinan Tinggi dan Pejabat Administrasi"},
        {"kode_klasifikasi":"KP.05.03","uraian_informasi":"Alih Tugas Pegawai"},
        {"kode_klasifikasi":"KP.05.03","uraian_informasi":"Usulan alih status, pindah instansi, pindah wilayah kerja, diperbantukan, dipekerjakan, penugasan sementara, mutasi antar perwakilan, mutasi ke dan dari perwakilan, pemindahan sementara, sampai dengan persetujuan\/pertimbangan pimpinan"},
        {"kode_klasifikasi":"KP.05.04","uraian_informasi":"Penetapan Perubahan Data Dasar\/Status\/Kedudukan Hukum Pegawai"},
        {"kode_klasifikasi":"KP.05.05","uraian_informasi":"Berkas Badan Pertimbangan Jabatan dan Pangkat (Baperjakat)"},
        {"kode_klasifikasi":"KP.05.06","uraian_informasi":"Pemberhentian Pegawai dengan Hormat"},
        {"kode_klasifikasi":"KP.05.06","uraian_informasi":"Pemberhentian pegawai dengan hormat baik atas permintaan sendiri atau bukan atas permintaan sendiri, baik dengan hak pensiun maupun tidak, mulai dari pengajuan permohonan sampai dengan dikeluarkannya Surat Keputusan (SK) Pensiun."},
        {"kode_klasifikasi":"KP.05.07","uraian_informasi":"Pemberhentian Sementara Pegawai"},
        {"kode_klasifikasi":"KP.05.08","uraian_informasi":"Pemberhentian Pegawai dengan Tuntutan Ganti Rugi"},
        {"kode_klasifikasi":"KP.05.09","uraian_informasi":"Pemberhentian Pegawai dan Penetapan Pensiun Pegawai"},
        {"kode_klasifikasi":"KP.05.09","uraian_informasi":"Pemberhentian Pegawai dan Penetapan Pensiun Pegawai termasuk di dalamnya Pensiun Duda\/Janda\/Anak dan Taspen"},
        {"kode_klasifikasi":"KP.05.10","uraian_informasi":"Pemberhentian dan Penetapan Pensiun Pejabat Pimpinan Tinggi dan Pejabat Negara"},
        {"kode_klasifikasi":"KP.06","uraian_informasi":"Administrasi Perseorangan"},
        {"kode_klasifikasi":"KP.06.01","uraian_informasi":"Berkas Perseorangan ASN"},
        {"kode_klasifikasi":"KP.06.02","uraian_informasi":"Berkas perseorangan Pegawai Pemerintah dengan Perjanjian Kerja"},
        {"kode_klasifikasi":"KP.06.03","uraian_informasi":"Berkas perseorangan Ketua\/Wakil Ketua\/Anggota BPK"},
        {"kode_klasifikasi":"KP.07","uraian_informasi":"Surat Perintah Dinas\/Surat Tugas serta Pertanggungjawabannya"},
        {"kode_klasifikasi":"KP.08","uraian_informasi":"Cuti Pegawai"},
        {"kode_klasifikasi":"KP.08.01","uraian_informasi":"Cuti Tahunan"},
        {"kode_klasifikasi":"KP.08.01","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti tahunan"},
        {"kode_klasifikasi":"KP.08.02","uraian_informasi":"Cuti Besar"},
        {"kode_klasifikasi":"KP.08.02","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti besar"},
        {"kode_klasifikasi":"KP.08.03","uraian_informasi":"Cuti Sakit"},
        {"kode_klasifikasi":"KP.08.03","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti sakit"},
        {"kode_klasifikasi":"KP.08.04","uraian_informasi":"Cuti Bersalin"},
        {"kode_klasifikasi":"KP.08.04","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti bersalin"},
        {"kode_klasifikasi":"KP.08.05","uraian_informasi":"Cuti Karena Alasan Penting"},
        {"kode_klasifikasi":"KP.08.05","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti alasan penting"},
        {"kode_klasifikasi":"KP.08.06","uraian_informasi":"Cuti di Luar Tanggungan Negara"},
        {"kode_klasifikasi":"KP.08.06","uraian_informasi":"Permintaan, pemberian dan pengurusan cuti di luar tanggungan negara"},
        {"kode_klasifikasi":"KP.09","uraian_informasi":"Pembinaan Pegawai"},
        {"kode_klasifikasi":"KP.09.01","uraian_informasi":"Sasaran Kerja Pegawai (SKP)"},
        {"kode_klasifikasi":"KP.09.01","uraian_informasi":"Penilaian kinerja pegawai"},
        {"kode_klasifikasi":"KP.09.02","uraian_informasi":"Penilaian Prestasi Kinerja"},
        {"kode_klasifikasi":"KP.09.02","uraian_informasi":"Penilaian Prestasi Kinerja termasuk yang berkaitan dengan pengajuan Daftar Usul Penetapan Angka Kredit\/Daftar Usul Penetapan Nilai Kinerja Jabatan Fungsional"},
        {"kode_klasifikasi":"KP.10","uraian_informasi":"Kehadiran atau ketidakhadiran pegawai\/rekapitulasi daftar hadir"},
        {"kode_klasifikasi":"KP.11","uraian_informasi":"Penyelesaian Pengelolaan Keberatan Pegawai"},
        {"kode_klasifikasi":"KP.12","uraian_informasi":"Dokumentasi Identitas Pegawai"},
        {"kode_klasifikasi":"KP.12.01","uraian_informasi":"Usul penetapan Kartu pegawai"},
        {"kode_klasifikasi":"KP.12.02","uraian_informasi":"Usul penetapan Kartu Pegawai Negeri Sipil Elektronik (KPE)"},
        {"kode_klasifikasi":"KP.12.03","uraian_informasi":"Usul penetapan Kartu Istri (Karis)\/Kartu Suami (Karsu)"},
        {"kode_klasifikasi":"KP.12.04","uraian_informasi":"Usul penetapan Keanggotaan Organisasi Profesi\/Kedinasan"},
        {"kode_klasifikasi":"KP.12.05","uraian_informasi":"Usul penetapan Laporan Pajak Penghasilan Pribadi (LP2P)"},
        {"kode_klasifikasi":"KP.12.06","uraian_informasi":"Keterangan Penerimaan Pembayaran Penghasilan Pegawai (KP4)"},
        {"kode_klasifikasi":"KP.12.07","uraian_informasi":"Daftar Urut Kepangkatan (DUK)"},
        {"kode_klasifikasi":"KP.13","uraian_informasi":"Penilaian Kompetensi"},
        {"kode_klasifikasi":"KP.13.01","uraian_informasi":"Standar dan Alat Ukur Penilaian Kompetensi"},
        {"kode_klasifikasi":"KP.13.01","uraian_informasi":"Standar Kompetensi Teknis, Alat Ukur Penilaian Kompetensi Teknis, Standar Kompetensi Perilaku, Alat Ukur Penilaian Assesment Kompetensi Perilaku"},
        {"kode_klasifikasi":"KP.13.02","uraian_informasi":"Sosialisasi dan Evaluasi Penilaian Kompetensi"},
        {"kode_klasifikasi":"KP.14","uraian_informasi":"Pengembangan Kompetensi"},
        {"kode_klasifikasi":"KP.14.01","uraian_informasi":"Tugas Belajar"},
        {"kode_klasifikasi":"KP.14.01","uraian_informasi":"Tugas belajar meliputi Proposal Kerjasama Beasiswa, Laporan Pengembangan Studi, SK Tugas Belajar, Program re-Entry"},
        {"kode_klasifikasi":"KP.14.02","uraian_informasi":"Izin Belajar"},
        {"kode_klasifikasi":"KP.14.03","uraian_informasi":"Penyelenggaraan Ujian Dinas\/Penyesuaian Ijazah\/Pengakuan Gelar"},
        {"kode_klasifikasi":"KP.15","uraian_informasi":"Kinerja Pegawai"},
        {"kode_klasifikasi":"KP.15.01","uraian_informasi":"Manajemen Kinerja dan Manajemen Presensi"},
        {"kode_klasifikasi":"KP.15.01","uraian_informasi":"Manajemen Kinerja, Manajemen Presensi meliputi Laporan dan Evaluasi Implementasi Manajemen Kinerja yang meliputi Laporan RKPP, Laporan Tahunan Manajemen Kinerja dan Manajemen Presentasi, Hasil Telaahan Penyesuaian Jam Kerja, Laporan Tahunan Manajemen Kinerja, Laporan Tahunan Manajemen Presensi"},
        {"kode_klasifikasi":"KP.15.02","uraian_informasi":"Pengurusan Satya Lencana Karya Satya\/Satya Lencana Wira Karya"},
        {"kode_klasifikasi":"KP.16","uraian_informasi":"Kesejahteraan Pegawai"},
        {"kode_klasifikasi":"KP.16.01","uraian_informasi":"Berkas Pengurusan Taspen dan Taperum"},
        {"kode_klasifikasi":"KP.16.02","uraian_informasi":"Mutasi Keluarga"},
        {"kode_klasifikasi":"KP.16.02","uraian_informasi":"Surat Izin Pernikahan\/Perceraian, Surat Nikah\/Cerai, Akta Kelahiran anak, Surat Keterangan Adopsi Anak, Surat Keterangan Meninggal Dunia"},
        {"kode_klasifikasi":"KP.17","uraian_informasi":"Pelayanan Kesehatan Pegawai"},
        {"kode_klasifikasi":"KP.17.01","uraian_informasi":"Berkas tentang Layanan Asuransi Pegawai\/BPJS"},
        {"kode_klasifikasi":"KP.17.02","uraian_informasi":"Pelaksanaan Tes Kesehatan Pegawai"},
        {"kode_klasifikasi":"KP.17.02","uraian_informasi":"Hasil Medical Check Up dan Tes Narkoba, persiapan dan laporan pelaksanaan Tes Kesehatan, hasil telaah medis\/pengujian kesehatan"},
        {"kode_klasifikasi":"KP.17.03","uraian_informasi":"Pelayanan Poliklinik dan Obat-obatan"},
        {"kode_klasifikasi":"KP.17.03","uraian_informasi":"Surat Izin Poliklinik, surat Izin Praktek Tenaga Medis, pengadaan dan pendistribusian obat-obatan, berkas tentang Medical Record, berkas tentang perawatan poliklinik, laporan kegiatan pelayanan medis"},
        {"kode_klasifikasi":"KP.17.04","uraian_informasi":"Pelayanan Konseling Pegawai"},
        {"kode_klasifikasi":"KP.17.04","uraian_informasi":"Berkas pelaksanaan konsultasi, perselisihan dan sengketa kepegawaian, mental pegawai, monitoring hasil konsultasi\/meditasi dan perkembangan hasil konsultasi\/meditasi"},
        {"kode_klasifikasi":"KP.17.05","uraian_informasi":"Berkas Penyelenggaraan Donor Darah"},
        {"kode_klasifikasi":"KP.18","uraian_informasi":"Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.01","uraian_informasi":"Penetapan Peran Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.02","uraian_informasi":"Pengangkatan Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.03","uraian_informasi":"Kenaikan Jenjang Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.04","uraian_informasi":"Pembebasan Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.05","uraian_informasi":"Pemberhentian Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.06","uraian_informasi":"Angka Kredit Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.06","uraian_informasi":"Pengajuan Daftar Usul Penetapan Angka Kredit, Penilaian Daftar Usul Penetapan Angka Kredit"},
        {"kode_klasifikasi":"KP.18.07","uraian_informasi":"Penilaian Karya Tulis Ilmiah Pejabat Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.08","uraian_informasi":"Pelaksanaan Konsultasi dan Fasilitasi terkait Implementasi Jabatan Fungsional Pemeriksa"},
        {"kode_klasifikasi":"KP.18.08","uraian_informasi":"Daftar Usulan Peserta Diklat Pembentukan jabatan Fungsional\/Peran, Daftar Usulan Peserta Assesment, Daftar Usulan Perubahan Peran, Laporan Pelaksanaan Konsultasi"},
        {"kode_klasifikasi":"KP.19","uraian_informasi":"Jabatan Funsgional Lainnya"},
        {"kode_klasifikasi":"KP.19.01","uraian_informasi":"Kajian Pembentukan Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.01","uraian_informasi":"Kajian penerapan jabatan fungsional lainnya, perangkat lunak internal BPK terkait JF lainnya, laporan hasil konsultasi dengan instansi pembina"},
        {"kode_klasifikasi":"KP.19.02","uraian_informasi":"Penetapan Peran Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.03","uraian_informasi":"Pengangkatan Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.04","uraian_informasi":"Kenaikan Jenjang Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.05","uraian_informasi":"Pembebasan Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.06","uraian_informasi":"Pemberhentian Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.07","uraian_informasi":"Angka Kredit Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.07","uraian_informasi":"Pengajuan Daftar Usul Penetapan Angka Kredit, Penilaian Daftar Usul Penetapan Angka Kredit"},
        {"kode_klasifikasi":"KP.19.08","uraian_informasi":"Penilaian Karya Tulis Ilmiah Pejabat Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.09","uraian_informasi":"Pelaksanaan Konsultasi dan Fasilitasi terkait Implementasi Jabatan Fungsional Lainnya"},
        {"kode_klasifikasi":"KP.19.09","uraian_informasi":"Daftar Usulan Peserta Diklat Pembentukan jabatan Fungsional\/Peran, Daftar Usulan Peserta Assesment, Daftar Usulan Perubahan Peran, Laporan Pelaksanaan Konsultasi"},
        {"kode_klasifikasi":"KU.00","uraian_informasi":"Anggaran Pendapatan dan Belanja Negara (APBN)"},
        {"kode_klasifikasi":"KU.00.01","uraian_informasi":"Kesepakatan Bersama Tiga Pihak BPK (selaku K\/L), Kementerian Keuangan dan Bappenas Mengenai Pagu Indikatif\/Sementara"},
        {"kode_klasifikasi":"KU.00.02","uraian_informasi":"Kesepakatan Bersama Tiga Pihak BPK (selaku K\/L), Kementerian Keuangan dan Bappenas Mengenai Pagu Definitif\/Alokasi Anggaran, Bahan Rapat Dengar Pendapat (RDP) dengan Komisi XI DPR RI, dan Persetujuan DPR Tentang Pagu Alokasi Anggaran"},
        {"kode_klasifikasi":"KU.00.03","uraian_informasi":"Dokumen Usulan dan Penetapan Target Penerimaan Negara"},
        {"kode_klasifikasi":"KU.00.04","uraian_informasi":"Penyusunan RKA-KL (BPK)"},
        {"kode_klasifikasi":"KU.00.04","uraian_informasi":"Kebijakan Umum, Renstra, Strategi dan Prioritas (Dokumen Rencana Strategis atas Rencana Kerja Jangka Panjang atau Rencana Kerja Lima Tahunan dan Dokumen Rencana Kerja (Renja) BPK)"},
        {"kode_klasifikasi":"KU.00.04","uraian_informasi":"Dokumen Rencana Kerja Anggaran Kementerian\/Lembaga (RKA-K\/L) BPK, Dokumen TOR, RKP\/RKSP, KAK, Beserta Dokumen Pendukungnya"},
        {"kode_klasifikasi":"KU.00.05","uraian_informasi":"Undang-Undang Anggaran Pendapatan dan Belanja Negara (APBN) dan Rencana Kerja Pemerintah (RKP)"},
        {"kode_klasifikasi":"KU.00.06","uraian_informasi":"Daftar Isian Pelaksanaan Anggaran (DIPA), Petunjuk Operasional Kegiatan (POK) dan Revisinya"},
        {"kode_klasifikasi":"KU.00.07","uraian_informasi":"Anggaran Pendapatan dan Belanja Perubahan (APBN-P)"},
        {"kode_klasifikasi":"KU.00.07","uraian_informasi":"Usulan Pemerintah Mengenai Rancangan Undang-Undang Anggaran Pendapatan dan Belanja Perubahan (RUU APBN-P), Bahan RDP dan Persetujuan Komisi XI DPR, Kesepakatan Bersama Tiga Pihak BPK (selaku K\/L), Kementerian Keuangan dan Bappenas Mengenai APBN-P, Bahan RDP dan Persetujuan Komisi XI DPR"},
        {"kode_klasifikasi":"KU.00.08","uraian_informasi":"Laporan Pemantauan Daftar Isian Pelaksanaan Anggaran\/ Petunjuk Operasional Kegiatan BPK"},
        {"kode_klasifikasi":"KU.01","uraian_informasi":"Pelaksanaan Anggaran"},
        {"kode_klasifikasi":"KU.01.01","uraian_informasi":"Ketentuan\/Peraturan Menteri Keuangan Menyangkut Pelaksanaan, Penatausahaan dan Pertanggungjawaban Anggaran"},
        {"kode_klasifikasi":"KU.01.02","uraian_informasi":"Dokumen Realisasi Pendapatan"},
        {"kode_klasifikasi":"KU.01.02","uraian_informasi":"Surat Setoran Pajak (SSP), Surat Setoran Bea dan Cukai (SSBC), Surat Setoran Bukan Pajak (SSBP) atau Bukti Setor Penerimaan Negara Bukan Pajak (PNBP), Bukti Setor Sisa Anggaran Lebih atau Surat Setoran Pengembalian Belanja (SSPB), Bukti Setor Bunga dan atau Jasa Giro Bank, Laporan Realisasi Pendapatan Negara dari masing-masing Satuan Kerja, Dokumen Penetapan Bagi Hasil Penerimaan Pajak antara Pusat dan Daerah, Dokumen Piutang Negara"},
        {"kode_klasifikasi":"KU.01.03","uraian_informasi":"Belanja"},
        {"kode_klasifikasi":"KU.01.03","uraian_informasi":"Dokumen Pelaksanaan Pengadaan Barang dan Jasa termasuk dokumen pembayarannya, Dokumen Pembayaran keuangan meliputi SPM, SP2D, dan lain-lain, Dokumen Tata Usaha Anggaran, Tunjangan\/Lembur\/ Honorarium\/Honorarium Pegawai Pemerintah dengan Perjanjian Kerja dan Pegawai Pemerintah Non Pegawai Negeri, Bukti Setor Iuran\/Kontribusi Pemerintah RI kepada Badan\/Organisasi Internasional, Dokumen Pembayaran Hutang Negara, Dokumen Akuntansi Keuangan, Laporan Keuangan Tahunan (LRA, LO, LPE, Neraca, CaLK), dokumen perjalanan dinas, dokumen diklat, dokumen bimtek, kebutuhan anggaran ASN"},
        {"kode_klasifikasi":"KU.02","uraian_informasi":"Gaji dan Tunjangan Pegawai"},
        {"kode_klasifikasi":"KU.02.01","uraian_informasi":"Remunerasi Pegawai"},
        {"kode_klasifikasi":"KU.02.01","uraian_informasi":"Kajian remunerasi, peringkat , daftar induk, daftar susulan, daftar rapel Tunjangan Kegiatan dan Pembinaan Khusus (TKPK)"},
        {"kode_klasifikasi":"KU.02.02","uraian_informasi":"Daftar Gaji Induk"},
        {"kode_klasifikasi":"KU.02.03","uraian_informasi":"Surat Keterangan Pemberhentian Pembayaran"},
        {"kode_klasifikasi":"KU.02.04","uraian_informasi":"Daftar Rincian Penghasilan"},
        {"kode_klasifikasi":"KU.02.05","uraian_informasi":"Pengurusan Kenaikan Gaji Berkala"},
        {"kode_klasifikasi":"KU.02.06","uraian_informasi":"Laporan Hutang pada Pihak Ketiga"},
        {"kode_klasifikasi":"KU.03","uraian_informasi":"Hibah Luar Negeri"},
        {"kode_klasifikasi":"KU.03","uraian_informasi":"Surat pernyataan telah menerima hibah, memo pencatatan penerimaan hibah langsung, dokumen registrasi hibah, dan lain-lain"},
        {"kode_klasifikasi":"KU.04","uraian_informasi":"Pengelolaan APBN"},
        {"kode_klasifikasi":"KU.04.01","uraian_informasi":"Keputusan Pengguna Anggaran tentang Penetapan (Kuasa Pengguna Anggaran, Kuasa Pengguna Barang\/Jasa, Pejabat Pembuat Komitmen"},
        {"kode_klasifikasi":"KU.04.02","uraian_informasi":"Pejabat Pembuat Daftar Gaji"},
        {"kode_klasifikasi":"KU.04.02","uraian_informasi":"Berkaitan dengan Pejabat Pembuat Daftar Gaji"},
        {"kode_klasifikasi":"KU.04.03","uraian_informasi":"Pejabat Penandatanganan SPM"},
        {"kode_klasifikasi":"KU.04.03","uraian_informasi":"Berkaitan dengan Pejabat Penandatanganan"},
        {"kode_klasifikasi":"KU.04.04","uraian_informasi":"Bendahara Penerimaan\/ Pengeluaran"},
        {"kode_klasifikasi":"KU.04.04","uraian_informasi":"Berkaitan dengan Bendahara Penerimaan\/ Pengeluaran"},
        {"kode_klasifikasi":"KU.04.05","uraian_informasi":"Pengelola Barang"},
        {"kode_klasifikasi":"KU.04.05","uraian_informasi":"Berkaitan dengan Pengelola Barang (Termasuk Berita Acara Serah Terima Jabatan)"},
        {"kode_klasifikasi":"KU.05","uraian_informasi":"Sisten Akutansi Instansi (SAI)"},
        {"kode_klasifikasi":"KU.05.01","uraian_informasi":"Manual Implementasi Sistem Akuntansi Instansi (SAI)"},
        {"kode_klasifikasi":"KU.05.02","uraian_informasi":"Kebijakan Akuntansi"},
        {"kode_klasifikasi":"PR.00","uraian_informasi":"Dokumen Perencanaan (Jangka Panjang dan Menengah)"},
        {"kode_klasifikasi":"PR.00.01","uraian_informasi":"Rencana Jangka Menengah (RJM) dan Rencana Strategis (Renstra) BPK"},
        {"kode_klasifikasi":"PR.00.02","uraian_informasi":"Rencana Implementasi Renstra (RIR) BPK"},
        {"kode_klasifikasi":"PR.00.03","uraian_informasi":"Bussiness Case Initiative Strategis"},
        {"kode_klasifikasi":"PR.00.04","uraian_informasi":"Rencana Strategis Satker Eselon I dan II"},
        {"kode_klasifikasi":"PR.01","uraian_informasi":"Dokumen Perencanaan (Operasional)"},
        {"kode_klasifikasi":"PR.01.01","uraian_informasi":"Usulan Satuan Kerja beserta data pendukung"},
        {"kode_klasifikasi":"PR.01.02","uraian_informasi":"Program Kerja Tahunan Satuan Kerja"},
        {"kode_klasifikasi":"PR.01.03","uraian_informasi":"Rencana Kegiatan Pemeriksaan"},
        {"kode_klasifikasi":"PR.01.04","uraian_informasi":"Rencana Kegiatan Setjen dan Penunjang (RKSP)"},
        {"kode_klasifikasi":"PR.01.05","uraian_informasi":"Rencana Kerja BPK (Renja)"},
        {"kode_klasifikasi":"PR.01.06","uraian_informasi":"Rencana Kerja Tahunan (RKT)"},
        {"kode_klasifikasi":"PR.01.07","uraian_informasi":"Acuan Penyusunan Prognosa"},
        {"kode_klasifikasi":"PR.01.08","uraian_informasi":"Standar Biaya Keluaran (SBK)"},
        {"kode_klasifikasi":"PR.01.09","uraian_informasi":"Pernyataan Komitmen Pencapaian Kinerja (PKPK)"},
        {"kode_klasifikasi":"PR.01.10","uraian_informasi":"Bahan Penyelenggaraan Rapat Kerja Perencanaan Operasional\/ Tahunan"},
        {"kode_klasifikasi":"PR.02","uraian_informasi":"Dokumen Laporan Berkala"},
        {"kode_klasifikasi":"PR.02.01","uraian_informasi":"Laporan Implementasi Renstra"},
        {"kode_klasifikasi":"PR.02.02","uraian_informasi":"Laporan Change Management"},
        {"kode_klasifikasi":"PR.02.03","uraian_informasi":"Laporan Sistem Informasi Manajemen dan Akuntansi (SIMAK)"},
        {"kode_klasifikasi":"PR.02.04","uraian_informasi":"Laporan Akuntabilitas Kinerja Pelaksana (LAKIP) BPK"},
        {"kode_klasifikasi":"PR.02.05","uraian_informasi":"Laporan Akuntabilitas Kinerja (LAK) Eselon I dan II"},
        {"kode_klasifikasi":"PR.02.06","uraian_informasi":"Laporan Kegiatan Pelaksana BPK"},
        {"kode_klasifikasi":"PR.02.07","uraian_informasi":"Laporan Pemantauan Pelaksanaan Rencana Pembangunan"},
        {"kode_klasifikasi":"PR.02.08","uraian_informasi":"Laporan Pemantauan Kegiatan Prioritas Kementerian\/Lembaga"},
        {"kode_klasifikasi":"PR.03","uraian_informasi":"Laporan Kegiatan"},
        {"kode_klasifikasi":"PR.03.01","uraian_informasi":"Laporan Rakor"},
        {"kode_klasifikasi":"PR.03.02","uraian_informasi":"Laporan Forum Eselon I"},
        {"kode_klasifikasi":"PR.03.03","uraian_informasi":"Laporan Hasil Survey Indikator Kinerja Utama (IKU) Indeks"},
        {"kode_klasifikasi":"PR.03.04","uraian_informasi":"Laporan Forum Manajer Indikator Kinerja Urama (IKU)"},
        {"kode_klasifikasi":"PR.03.05","uraian_informasi":"Laporan Rapat Kerja (Raker)"},
        {"kode_klasifikasi":"PR.03.06","uraian_informasi":"Laporan Hasil Survey Awareness, Desire, Knowledge, Ability, Reinforcement (ADKAR)"},
        {"kode_klasifikasi":"PR.03.07","uraian_informasi":"Laporan Insidental Lainnya"},
        {"kode_klasifikasi":"PR.04","uraian_informasi":"Evaluasi Program\/Kegiatan"},
        {"kode_klasifikasi":"PR.04.01","uraian_informasi":"Evaluasi Program\/Kegiatan Satuan Kerja"},
        {"kode_klasifikasi":"PR.04.02","uraian_informasi":"Evaluasi Program\/Kegiatan BPK"},
        {"kode_klasifikasi":"HK.00","uraian_informasi":"Kebijakan Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.00.01","uraian_informasi":"Pembentukan Peraturan Perundang-undangan (Regeling)"},
        {"kode_klasifikasi":"HK.00.02","uraian_informasi":"Dokumen Hukum"},
        {"kode_klasifikasi":"HK.00.03","uraian_informasi":"Pembentukan Keputusan\/Penetapan (Beschikking)"},
        {"kode_klasifikasi":"HK.00.04","uraian_informasi":"Publikasi Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.00.05","uraian_informasi":"Kerjasama Hukum"},
        {"kode_klasifikasi":"HK.00.06","uraian_informasi":"Uji Materi Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.01","uraian_informasi":"Pembentukan Peraturan Perundang-undangan yang Berhubungan dengan Pelaksanaan Tugas BPK beserta Naskah Akademiknya\/Regeling"},
        {"kode_klasifikasi":"HK.01.01","uraian_informasi":"Perencanaan Pembentukan Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.01.01","uraian_informasi":"Usul Prakarsa Peraturan Perundang-undangan, Bahan\/Materi Program Legislasi Nasional dari Instansi Pusat, Program Legislasi Instansi Pusat"},
        {"kode_klasifikasi":"HK.01.02","uraian_informasi":"Penyusunan Peraturan Perundang-undangan, Naskah Akademik Peraturan"},
        {"kode_klasifikasi":"HK.01.02","uraian_informasi":"Tanggapan\/Pendapat Para Ahli terhadap Peraturan Perundang-undangan, Materi Pembahasan Rancangan Peraturan Perundang-undangan di Lembaga Pengusul, Materi Pembahasan Rancangan Peraturan Perundang-undangan di Legislatif, Keterangan, Jawab Pemerintah mengenai Rancangan Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.01.03","uraian_informasi":"Pembahasan Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.01.03","uraian_informasi":"Permohonan RPP (R Perpu, R Perpres), Tanggapan Rancangan Peraturan Perundang-undangan (RUU, RPP, Perpres), Penyampaian Hasil Pengharmonisan, Pembulatan dan Pemantapan Konsepsi Peraturan Perundang-undangan dan Draft Akhir."},
        {"kode_klasifikasi":"HK.01.04","uraian_informasi":"Pengesahan dan Penetapan"},
        {"kode_klasifikasi":"HK.01.04","uraian_informasi":"Pemberian Paraf oleh Lembaga Terkait, Penandatangan Draft Final oleh Pimpinan Lembaga Pengusul, Penandatangan oleh Pejabat yang Menetapkan"},
        {"kode_klasifikasi":"HK.01.05","uraian_informasi":"Pengundangan"},
        {"kode_klasifikasi":"HK.01.05","uraian_informasi":"Permohonan Pengajuan Pengundangan pada Lembaran Negara Republik Indonesia dan Tambahan Lembaran Negara Republik Indonesia"},
        {"kode_klasifikasi":"HK.02","uraian_informasi":"Kerjasama Hukum\/Nota Kesepahaman\/Memorandum of Understanding (MoU)\/Agreement"},
        {"kode_klasifikasi":"HK.02.01","uraian_informasi":"Usul Prakarsa dari Lembaga\/Unit Kerja"},
        {"kode_klasifikasi":"HK.02.02","uraian_informasi":"Konsultasi dan koordinasi kerjasama hukum"},
        {"kode_klasifikasi":"HK.02.03","uraian_informasi":"Rapat Interdep\/Antar Unit"},
        {"kode_klasifikasi":"HK.02.04","uraian_informasi":"Draft\/Counter Draft"},
        {"kode_klasifikasi":"HK.02.05","uraian_informasi":"Penjajakan, Perundingan, Perumusan Naskah, Penerimaan\/ Pemarafan"},
        {"kode_klasifikasi":"HK.02.06","uraian_informasi":"Draft Final"},
        {"kode_klasifikasi":"HK.02.07","uraian_informasi":"Penandatanganan"},
        {"kode_klasifikasi":"HK.02.08","uraian_informasi":"Kerja Sama\/Nota Kesepahaman\/MoU"},
        {"kode_klasifikasi":"HK.02.08","uraian_informasi":"Kegiatan Kerja Sama\/Nota Kesepahaman\/MoU seperti perjanjian kerja sama dalam negeri\/luar negeri\/diklat mulai dari persiapan, penandatanganan sampai dengan evaluasi naskah kerja sama, MoU pengadaan barang dan jasa, proporsal kerjasama beasiswa, Mou\/Agreement dengan Lembaga Pemeriksa di Luar Negeri\/Organisasi Donor Internasional, MoU dengan Perguruan Tinggi atau instansi terkait, dan lain-lain."},
        {"kode_klasifikasi":"HK.03","uraian_informasi":"Dokumentasi Hukum"},
        {"kode_klasifikasi":"HK.03.01","uraian_informasi":"Sistem jaringan Dokumentasi dan Informasi Hukum (SJDIH)"},
        {"kode_klasifikasi":"HK.03.02","uraian_informasi":"Inventarisasi Peraturan Perundang-undangan dan Bahan Hukum Lainnya"},
        {"kode_klasifikasi":"HK.03.03","uraian_informasi":"Pengolahan Peraturan Perundang-undangan dalam Bentuk Hardcopy"},
        {"kode_klasifikasi":"HK.03.03","uraian_informasi":"Katalogisasi Peraturan Perundang-undangan, Abstraksi Peraturan Perundang-undangan, Katalogisasi Monografi Hukum, Bahan perundang-undangan (Raw Data)"},
        {"kode_klasifikasi":"HK.03.04","uraian_informasi":"Pengolahan Peraturan Perundang-undangan dan Bahan Hukum lainnya dalam Bentuk Online melalui : Website\/Jaringan, Back Up, Database"},
        {"kode_klasifikasi":"HK.03.05","uraian_informasi":"Evaluasi dan pemantauan pengelola JDIH"},
        {"kode_klasifikasi":"HK.03.06","uraian_informasi":"Pertemuan berkala pengelola JDIH"},
        {"kode_klasifikasi":"HK.04","uraian_informasi":"Uji Materi Peraturan Perundang-undangan"},
        {"kode_klasifikasi":"HK.04.01","uraian_informasi":"Pengajuan Permohonan"},
        {"kode_klasifikasi":"HK.04.02","uraian_informasi":"Pendaftaran"},
        {"kode_klasifikasi":"HK.04.03","uraian_informasi":"Penjadwalan Sidang"},
        {"kode_klasifikasi":"HK.04.04","uraian_informasi":"Pemeriksaan Pendahuluan"},
        {"kode_klasifikasi":"HK.04.05","uraian_informasi":"Pemeriksaan Persidangan"},
        {"kode_klasifikasi":"HK.04.06","uraian_informasi":"Putusan"},
        {"kode_klasifikasi":"HK.05","uraian_informasi":"Dokumen Tindak Lanjut Hasil Pemeriksaan Laporan Keuangan (LK) BPK oleh Kantor Akuntan Publik (KAP)"},
        {"kode_klasifikasi":"HK.06","uraian_informasi":"Kompilasi Dokumen Penanganan Gugatan Perdata"},
        {"kode_klasifikasi":"HK.07","uraian_informasi":"Kompilasi Dokumen Penanganan Gugatan Tata Usaha Negara"},
        {"kode_klasifikasi":"HK.08","uraian_informasi":"Laporan Pendampingan Hukum Ahli\/Saksi"},
        {"kode_klasifikasi":"HK.09","uraian_informasi":"Pendapat Hukum dan Dokumen Pendukungnya"},
        {"kode_klasifikasi":"HK.10","uraian_informasi":"Kompilasi Kajian\/Pendapat Hukum\/Perdata\/Tata Usaha Negara\/Pidana"},
        {"kode_klasifikasi":"HK.11","uraian_informasi":"Laporan Kegiatan yang Berkaitan dengan Pelaksanaan Tugas Kedinasan"},
        {"kode_klasifikasi":"HK.11.01","uraian_informasi":"Judical Review terkait Permohonan Pengujian Peraturan Perundang-undangan tentang Keuangan Negara dan BPK"},
        {"kode_klasifikasi":"HK.11.02","uraian_informasi":"Sengketa Kewenangan Antar Lembaga"},
        {"kode_klasifikasi":"HK.11.03","uraian_informasi":"Penyusunan dan Pembahasan RUU Perubahan Peraturan Perundang-undangan tentang Keuangan Negara dan BPK"},
        {"kode_klasifikasi":"HK.12","uraian_informasi":"Laporan Kegiatan Penelitian Hukum atas Peraturan\/Rancangan Peraturan di Lingkungan BPK dalam Rangka Harmonisasi dan Sinkronisasi Penerbitan Produk Hukum BPK"},
        {"kode_klasifikasi":"HK.13","uraian_informasi":"Kajian Hukum serta Data\/Dokumen Pendukung Kajian"},
        {"kode_klasifikasi":"HK.14","uraian_informasi":"Bahan Sidang Badan"},
        {"kode_klasifikasi":"HK.15","uraian_informasi":"Tata Naskah beserta Verbal"},
        {"kode_klasifikasi":"HK.15.01","uraian_informasi":"Peraturan BPK"},
        {"kode_klasifikasi":"HK.15.02","uraian_informasi":"Keputusan BPK"},
        {"kode_klasifikasi":"HK.15.02","uraian_informasi":"Keputusan BPK yang Bersifat Pengaturan, Keputusan BPK yang Bersifat Penetapan"},
        {"kode_klasifikasi":"HK.15.03","uraian_informasi":"Keputusan Ketua BPK"},
        {"kode_klasifikasi":"HK.15.04","uraian_informasi":"Keputusan Wakil Ketua BPK"},
        {"kode_klasifikasi":"HK.15.05","uraian_informasi":"Keputusan Sekretaris Jenderal BPK"},
        {"kode_klasifikasi":"HK.15.05","uraian_informasi":"Keputusan Sekretaris Jenderal BPK yang Bersifat Pengaturan, Keputusan Sekretaris Jenderal BPK yang Bersifat Penetapan"},
        {"kode_klasifikasi":"HK.15.06","uraian_informasi":"Instruksi Dinas Sekretaris Jenderal BPK"},
        {"kode_klasifikasi":"HK.15.07","uraian_informasi":"Surat Edaran Sekretaris Jenderal BPK"},
        {"kode_klasifikasi":"HK.15.08","uraian_informasi":"Pengumuman Sekretaris Jenderal BPK"},
        {"kode_klasifikasi":"HK.15.09","uraian_informasi":"Peraturan\/Keputusan Bersama Sekretaris Jenderal BPK"},
        {"kode_klasifikasi":"HK.15.10","uraian_informasi":"Keputusan Kepala Perwakilan"},
        {"kode_klasifikasi":"HK.15.11","uraian_informasi":"Instruksi Dinas Kepala Perwakilan"},
        {"kode_klasifikasi":"HK.15.12","uraian_informasi":"Surat Edaran Kepala Perwakilan"},
        {"kode_klasifikasi":"HK.15.13","uraian_informasi":"Pengumuman Kepala Perwakilan"},
        {"kode_klasifikasi":"HK.16","uraian_informasi":"Kajian Legislasi"},
        {"kode_klasifikasi":"HK.17","uraian_informasi":"Bantuan\/Konsultasi Hukum dengan Tim Pemeriksa dan\/atau Narasumber dari Luar"},
        {"kode_klasifikasi":"HK.18","uraian_informasi":"Ekspose Gelar Perkara dengan Aparat Penegak Hukum"},
        {"kode_klasifikasi":"HK.19","uraian_informasi":"Jawaban\/Tanggapan atas Disposisi Peminta Pendapat"},
        {"kode_klasifikasi":"HK.20","uraian_informasi":"Validasi Surat Keluar Wakil Ketua kepada Aparat Penegak Hukum"},
        {"kode_klasifikasi":"HK.21","uraian_informasi":"Kepaniteraan Majelis Tuntutan Perbendaharaan (MTP)"},
        {"kode_klasifikasi":"HK.21.01","uraian_informasi":"Konsep Pertimbangan Hukum Kasus Kerugian Negara oleh Bendahara"},
        {"kode_klasifikasi":"HK.21.02","uraian_informasi":"Bahan Sidang"},
        {"kode_klasifikasi":"HK.21.03","uraian_informasi":"Undangan Sidang"},
        {"kode_klasifikasi":"HK.21.04","uraian_informasi":"Produk Pasca Sidang"},
        {"kode_klasifikasi":"HK.21.05","uraian_informasi":"Administrasi Kepaniteraan misal Register Perkara, Penomoran Undangan, Buku Ekspedisi MTP"},
        {"kode_klasifikasi":"HK.22","uraian_informasi":"Pemberian Pertimbangan Hukum Kasus Kerugian Negara\/Daerah Non Bendahara"},
        {"kode_klasifikasi":"HK.23","uraian_informasi":"Pemberian Rekomendasi Penghapusan Piutang Negara\/Daerah"},
        {"kode_klasifikasi":"HK.24","uraian_informasi":"Kompilasi Data Laporan Hasil Pemantauan Penyelesaian Kerugian Negara\/Daerah"},
        {"kode_klasifikasi":"HK.25","uraian_informasi":"Hasil Pemantauan Penanganan Hasil Pemeriksaan BPK yang Disampaikan kepada Instansi yang Berwenang"},
        {"kode_klasifikasi":"HK.26","uraian_informasi":"Dokumen Kasus-Kasus Khusus\/Sengketa Hukum:"},
        {"kode_klasifikasi":"HK.26.01","uraian_informasi":"Perdata"},
        {"kode_klasifikasi":"HK.26.02","uraian_informasi":"Tata Usaha Negara"},
        {"kode_klasifikasi":"HK.26.03","uraian_informasi":"Arbitrase"},
        {"kode_klasifikasi":"HK.27","uraian_informasi":"Buku-Buku Produk BPK (Kompilasi Pendapat Hukum)"},
        {"kode_klasifikasi":"HK.27","uraian_informasi":"Buku-Buku Produk BPK (Kompilasi Pendapat Hukum, dan lain-lain)"},
        {"kode_klasifikasi":"HK.28","uraian_informasi":"Program Legislasi"},
        {"kode_klasifikasi":"HK.28.01","uraian_informasi":"Bahan\/Materi Program Legislasi Nasional dari Instansi"},
        {"kode_klasifikasi":"HK.28.02","uraian_informasi":"Program Legislasi Lembaga\/Instansi"},
        {"kode_klasifikasi":"HK.29","uraian_informasi":"Rancangan Peraturan Perundang-undangan\/Peraturan Pemerintah Pengganti Undang-undang"},
        {"kode_klasifikasi":"HK.29","uraian_informasi":"Rancangan Undang-undang atau Peraturan Pemerintah Pengganti Undang-undang termasuk Naskah Akademik, Rancangan Awal sampai dengan Rancangan Akhir dan Telaah Hukum sampai diundangkan"},
        {"kode_klasifikasi":"HK.30","uraian_informasi":"Hukum dan Penyelesaian Sanggah"},
        {"kode_klasifikasi":"HK.30.01","uraian_informasi":"Bantuan Hukum\/Konsultasi Hukum\/Advokasi"},
        {"kode_klasifikasi":"HK.30.01","uraian_informasi":"Pemberian Bantuan\/ Konsultasi Hukum (pidana, perdata, tata usaha negara dan agama)"},
        {"kode_klasifikasi":"HK.30.02","uraian_informasi":"Penanganan Permasalahan Hukum"},
        {"kode_klasifikasi":"HK.30.02","uraian_informasi":"Penanganan Permasalahan Kontrak, Keterangan Ahli"},
        {"kode_klasifikasi":"OT.00","uraian_informasi":"Organisasi"},
        {"kode_klasifikasi":"OT.00.01","uraian_informasi":"Analisis Organisasi"},
        {"kode_klasifikasi":"OT.00.02","uraian_informasi":"Evaluasi Organisasi"},
        {"kode_klasifikasi":"OT.01","uraian_informasi":"Perumusan Kebijakan Penelitian, Pengkajian, Pengembangan, Perekayasaan, Penerapan serta Pendayagunaan Ilmu Pengetahuan dan Teknologi"},
        {"kode_klasifikasi":"OT.01.01","uraian_informasi":"Pengkajian dan Pengusulan Kebijakan"},
        {"kode_klasifikasi":"OT.01.02","uraian_informasi":"Penyiapan Kebijakan"},
        {"kode_klasifikasi":"OT.01.03","uraian_informasi":"Perumusan dan Penyusunan Bahan"},
        {"kode_klasifikasi":"OT.01.04","uraian_informasi":"Penetapan dalam Bentuk NSPK (Norma Standar Prosedur dan Kriteria)"},
        {"kode_klasifikasi":"OT.02","uraian_informasi":"Penelitian dan Pengkajian"},
        {"kode_klasifikasi":"OT.02.01","uraian_informasi":"Rencana Kerja"},
        {"kode_klasifikasi":"OT.02.01","uraian_informasi":"Master Plan\/Rencana Strategis, Rencana Kerja Tahunan (Proposal\/Idea Concept Paper (ICP), Material Transfer Agreement (MTA), Perijinan Penelitian)"},
        {"kode_klasifikasi":"OT.02.02","uraian_informasi":"Administrasi Penelitian"},
        {"kode_klasifikasi":"OT.02.02","uraian_informasi":"Surat Tugas\/Surat Perintah, Pembentukan Tim Kerja, Dokumen\/Formulir Pendukung\/Instruksi, Persiapan Survey, Penggunaan Peralatan (Alat dan Bahan) dan lain-lain."},
        {"kode_klasifikasi":"OT.02.03","uraian_informasi":"Pelaksanaan Penelitian\/Pengkajian"},
        {"kode_klasifikasi":"OT.02.03","uraian_informasi":"Prosedur\/Petunjuk, Data Primer, Log Book, Studi Kelayakan, Instrumen Penelitian, Pelaksanaan Survey, Laporan Hasil Pendataan\/Survey, Analisis\/Pengolahan Data, Laporan Hasil Studi Banding, Focus Group Discussion (FGD), Survey, Masukan\/Pertimbangan dari Pihak Internal Masukan\/Konsultasi dari Narasumber\/Konsultan, Pendapat Ahli atau Pihak Luar lainnya"},
        {"kode_klasifikasi":"OT.02.04","uraian_informasi":"Hasil Penelitian\/Pengkajian\/Rekomendasi"},
        {"kode_klasifikasi":"OT.02.05","uraian_informasi":"Hasil Penelitian dan Pengkajian Hasil Jasa Layanan"},
        {"kode_klasifikasi":"OT.03","uraian_informasi":"Pengembangan dan Inovasi"},
        {"kode_klasifikasi":"OT.03.01","uraian_informasi":"Rencana Kerja Pengembangan dan Inovasi"},
        {"kode_klasifikasi":"OT.03.02","uraian_informasi":"Administrasi Pengembangan dan Inovasi"},
        {"kode_klasifikasi":"OT.03.03","uraian_informasi":"Pelaksanaan Pengembangan dan Inovasi"},
        {"kode_klasifikasi":"OT.03.04","uraian_informasi":"Hasil Pengembangan Inovasi"},
        {"kode_klasifikasi":"OT.03.05","uraian_informasi":"Advokasi dan Fasilitasi Penelitian Pengembangan dan Inovasi"},
        {"kode_klasifikasi":"OT.04","uraian_informasi":"Public Hearing, Diseminasi Hasil Penelitian, Pengkajian dan Pengembangan"},
        {"kode_klasifikasi":"OT.04","uraian_informasi":"Public Hearing (Pemberian Masukan\/Uji Petik\/Hearing dan Dukungan dalam Penyusunan Kebijakan), Diseminasi Hasil Penelitian, Pengkajian dan Pengembangan"},
        {"kode_klasifikasi":"OT.05","uraian_informasi":"Perangkat Lunak Non Pemeriksaan dalam Bidang Organisasi (Pedoman, Juklak, Juknis, Panduan, Seri Panduan dan sebagainya)"},
        {"kode_klasifikasi":"OT.06","uraian_informasi":"Perangkat Lunak Non Pemeriksaan dalam Bidang Tata Laksana\/Sistem Prosedur (Pedoman, Juklak, Juknis, Panduan, Seri Panduan dan sebagainya)"},
        {"kode_klasifikasi":"OT.07","uraian_informasi":"Dokumen Perangkat Lunak Lainnya yang di Inisiasi oleh Satker"},
        {"kode_klasifikasi":"OT.08","uraian_informasi":"Perangkat Lunak Pemeriksaan (Pedoman, Juklak, Juknis, Panduan, Seri Panduan dan sebagainya)"},
        {"kode_klasifikasi":"OT.09","uraian_informasi":"Perangkat Lunak Pemeriksaan (Pedoman, Juklak, Juknis, Pola Hubungan Kerja dan sebagainya) terkait Jabatan Fungsional"},
        {"kode_klasifikasi":"OT.10","uraian_informasi":"Hasil Reviu\/Kajian atas Perangkat Lunak Satker termasuk di dalamnya Draft Perbaikan, Surat Menyurat dan Reviu atas Analisis Kebutuhan"},
        {"kode_klasifikasi":"OT.11","uraian_informasi":"Forum Komunikasi Penelitian dan Pengembangan"},
        {"kode_klasifikasi":"OT.12","uraian_informasi":"Jurnal Penelitian, Pengembangan dan Penerapan Ilmu Pengetahuan dan Teknologi"},
        {"kode_klasifikasi":"OT.12","uraian_informasi":"Penerbitan: Jurnal\/Buletin Ilmiah, Bahan Publikasi Khusus, Leafet, Booklet, Kamus Istilah"},
        {"kode_klasifikasi":"OT.13","uraian_informasi":"Hak Atas Kekayaan Intelektual (HAKI)"},
        {"kode_klasifikasi":"OT.14","uraian_informasi":"Tata Laksana"},
        {"kode_klasifikasi":"OT.14.01","uraian_informasi":"Penyusunan dan Penyelarasan Proses Bisnis"},
        {"kode_klasifikasi":"OT.14.02","uraian_informasi":"Evaluasi Proses Bisnis"},
        {"kode_klasifikasi":"OT.14.03","uraian_informasi":"Penyusunan dan Penyelarasan SOP"},
        {"kode_klasifikasi":"OT.14.03","uraian_informasi":"Prosedur kerja secara rinci, tahap demi tahap dan sistematis tentang kegiatan rutin yang dapat dilengkapi dengan referensi, lampiran, formulir, diagram alir dan alur kerja (flowchart)."},
        {"kode_klasifikasi":"OT.14.04","uraian_informasi":"Monitoring dan Evaluasi SOP"},
        {"kode_klasifikasi":"OT.14.04","uraian_informasi":"Monitoring dan evaluasi penerapan SOP di unit kerja"},
        {"kode_klasifikasi":"KA.00","uraian_informasi":"Penyusunan Sistem Kearsipan"},
        {"kode_klasifikasi":"KA.00.01","uraian_informasi":"Tata Naskah Dinas"},
        {"kode_klasifikasi":"KA.00.01","uraian_informasi":"Pengurusan dan pengendalian Naskah Dinas, dan lain-lain"},
        {"kode_klasifikasi":"KA.00.02","uraian_informasi":"Klasifikasi Arsip"},
        {"kode_klasifikasi":"KA.00.03","uraian_informasi":"Jadwal Retensi Arsip"},
        {"kode_klasifikasi":"KA.00.04","uraian_informasi":"Sistem Klasifikasi Keamanan Arsip Dinamis (SKKAD)"},
        {"kode_klasifikasi":"KA.01","uraian_informasi":"Pengelolaan Arsip Dinamis"},
        {"kode_klasifikasi":"KA.01.01","uraian_informasi":"Penciptaan"},
        {"kode_klasifikasi":"KA.01.01","uraian_informasi":"Penciptaan meliputi kegiatan administrasi persuratan bersifat rahasia seperti pengurusan\/pengelolaan Nota Dinas\/Memo\/surat masuk dan surat keluar, kegiatan penomoran surat, pengarahan, pencatatan, dan penditribusian surat, penggunaan cap\/stempel dan pengiriman surat\/barang cetakan, penggunaan kartu kendali, buku agenda, lembar pengantar\/buku ekspedisi, formulir catatan permintaan dan layanan penggandaan dokumen\/arsip serta penggunaan instrumen Tata Naskah Dinas, Klasifikasi Arsip dan SKAAD"},
        {"kode_klasifikasi":"KA.01.01","uraian_informasi":"Penciptaan meliputi kegiatan administrasi persuratan bersifat terbatas seperti pengurusan\/pengelolaan Nota Dinas\/Memo\/surat masuk dan surat keluar, kegiatan penomoran surat, pengarahan, pencatatan, dan penditribusian surat, penggunaan cap\/stempel dan pengiriman surat\/barang cetakan, penggunaan kartu kendali, buku agenda, lembar pengantar\/buku ekspedisi, formulir catatan permintaan dan layanan penggandaan dokumen\/arsip serta penggunaan instrumen Tata Naskah Dinas, Klasifikasi Arsip dan SKAAD"},
        {"kode_klasifikasi":"KA.01.02","uraian_informasi":"Penggunaan"},
        {"kode_klasifikasi":"KA.01.02","uraian_informasi":"Penggunaan instrumen Sistem Klasifikasi Keamanan dan Akses Arsip Dinamis (SKKAD)"},
        {"kode_klasifikasi":"KA.01.03","uraian_informasi":"Pemeliharaan"},
        {"kode_klasifikasi":"KA.01.03","uraian_informasi":"Pemberkasan arsip aktif, penyimpanan arsip aktif, penataan arsip inaktif, penyimpanan arsip inaktif, alih media arsip dan penggunaan instrumen Klasifikasi Arsip"},
        {"kode_klasifikasi":"KA.01.04","uraian_informasi":"Penyusutan"},
        {"kode_klasifikasi":"KA.01.04","uraian_informasi":"a. Pemindahan arsip inaktif serta penggunaan instrumen Jadwal Retensi Arsip (JRA)"},
        {"kode_klasifikasi":"KA.01.04","uraian_informasi":"b. Pemusnahan arsip inaktif serta penggunaan instrumen Jadwal Retensi Arsip (JRA)"},
        {"kode_klasifikasi":"KA.01.04","uraian_informasi":"c. Akuisisi arsip inaktif serta penggunaan instrumen Jadwal Retensi Arsip (JRA)"},
        {"kode_klasifikasi":"KA.01.05","uraian_informasi":"Pengolahan dan penyajian arsip menjadi informasi"},
        {"kode_klasifikasi":"KA.01.06","uraian_informasi":"Peminjaman dan pengembalian Arsip Aktif"},
        {"kode_klasifikasi":"KA.01.07","uraian_informasi":"Peminjaman dan pengembalian Arsip Inaktif"},
        {"kode_klasifikasi":"KA.02","uraian_informasi":"Konsultasi, Supervisi dan Impelementasi Sistem Kearsipan"},
        {"kode_klasifikasi":"KA.02.01","uraian_informasi":"Data Unit Kearsipan"},
        {"kode_klasifikasi":"KA.02.02","uraian_informasi":"Data Unit Pengolah"},
        {"kode_klasifikasi":"KA.02.03","uraian_informasi":"Supervisi Kearsipan"},
        {"kode_klasifikasi":"KA.02.03","uraian_informasi":"Supervisi penerapan sistem kearsipan, penggunaan sarana dan prasarana kearsipan, SDM kearsipan, penyusunan sistem pengelolaan arsip manual maupun elektronik mulai dari persiapan, pelaksanaan, pelaporan di Unit Pengolah dan Unit Kearsipan"},
        {"kode_klasifikasi":"KA.03","uraian_informasi":"Apresiasi Kearsipan"},
        {"kode_klasifikasi":"KA.03","uraian_informasi":"Mulai dari persiapan, pelaksanaan, pelaporan dan evaluasi"},
        {"kode_klasifikasi":"KA.04","uraian_informasi":"Asosiasi Arsiparis"},
        {"kode_klasifikasi":"KA.05","uraian_informasi":"Pengembangan Sistem Pengelolaan Arsip Kepegawaian"},
        {"kode_klasifikasi":"KA.05","uraian_informasi":"Pedoman penataan arsip kepegawaian, petunjuk teknis penataan arsip kepegawaian, database dan berkas pelayanan arsip kepegawaian"},
        {"kode_klasifikasi":"KA.06","uraian_informasi":"Monitoring dan Evaluasi Sistem Kearsipan"},
        {"kode_klasifikasi":"KA.06","uraian_informasi":"Pelaksanaan kegiatan monitoring dan evaluasi sistem kearsipan mulai dari perencanaan, pelaksanaan, hingga pelaporan kegiatan monitoring dan evaluasi sistem kearsipan"},
        {"kode_klasifikasi":"TU.00","uraian_informasi":"Daftar Alamat Pendistribusian Ikhtisar Hasil Pemeriksaan (IHPS) Instansi Pusat dan Daerah serta Resi Pengiriman"},
        {"kode_klasifikasi":"TU.00","uraian_informasi":"Daftar Alamat Pendistribusian Hapsem\/IHPS Instansi Pusat dan Daerah serta Resi Pengiriman"},
        {"kode_klasifikasi":"TU.01","uraian_informasi":"Perjalanan Dinas"},
        {"kode_klasifikasi":"TU.01.01","uraian_informasi":"Dalam Negeri"},
        {"kode_klasifikasi":"TU.01.01","uraian_informasi":"Dokumen Perjalanan Dinas Dalam Negeri"},
        {"kode_klasifikasi":"TU.01.02","uraian_informasi":"Luar Negeri"},
        {"kode_klasifikasi":"TU.01.02","uraian_informasi":"Dokumen Perjalanan Dinas Luar Negeri"},
        {"kode_klasifikasi":"TU.02","uraian_informasi":"Pengurusan Dokumen Luar Negeri"},
        {"kode_klasifikasi":"TU.02","uraian_informasi":"Proses Pembuatan Surat Persetujuan, Dokumen Pembuatan Visa\/Paspor & FC Visa"},
        {"kode_klasifikasi":"TU.03","uraian_informasi":"Rapat"},
        {"kode_klasifikasi":"TU.03.01","uraian_informasi":"Rapat Pimpinan"},
        {"kode_klasifikasi":"TU.03.01","uraian_informasi":"Kegiatan rapat dalam bentuk risalah\/notulen"},
        {"kode_klasifikasi":"TU.03.02","uraian_informasi":"Rapat Staf"},
        {"kode_klasifikasi":"TU.03.02","uraian_informasi":"Hasil kegiatan rapat staf dalam bentuk risalah\/notulen"},
        {"kode_klasifikasi":"TU.03.03","uraian_informasi":"Rapat Koodinasi"},
        {"kode_klasifikasi":"TU.03.03","uraian_informasi":"Hasil kegiatan rapat koordinasi"},
        {"kode_klasifikasi":"RT.00","uraian_informasi":"Fasilitas"},
        {"kode_klasifikasi":"RT.00.01","uraian_informasi":"Kendaraan Dinas"},
        {"kode_klasifikasi":"RT.00.01","uraian_informasi":"Pengelolaan kendaraan dinas seperti formulir permohonan penggunaan\/peminjaman kendaraan dinas, laporan kehilangan kendaraan, pengurusan surat-surat kendaraan termasuk bukti kepemilikan (BPKB, STNK) dan pemeliharaan kendaraan dinas"},
        {"kode_klasifikasi":"RT.00.02","uraian_informasi":"Ruang Rapat\/Gedung"},
        {"kode_klasifikasi":"RT.00.02","uraian_informasi":"Penggunaan fasilitas kantor meliputi permintaan dan penggunaan\/peminjaman ruang rapat\/gedung berikut sarana kelengkapannya dan fasilitas sarpras lainnya."},
        {"kode_klasifikasi":"RT.00.03","uraian_informasi":"Telekomunikasi"},
        {"kode_klasifikasi":"RT.00.03","uraian_informasi":"Penggunaan\/langganan peralatan telekomunikasi meliputi: telepon, faksimile, radio, teleks, TV kabel, internet dan administrasinya"},
        {"kode_klasifikasi":"RT.00.04","uraian_informasi":"Instalasi\/Jaringan"},
        {"kode_klasifikasi":"RT.00.04","uraian_informasi":"Instalasi listrik, air, telepon, Local Area Network (LAN), komputer termasuk pemasangannya"},
        {"kode_klasifikasi":"RT.00.05","uraian_informasi":"Perlengkapan Kantor"},
        {"kode_klasifikasi":"RT.00.05","uraian_informasi":"Penyediaan perlengkapan kantor seperti PC komputer, laptop, meja, kursi, lemari, rak filing cabinet, brankas dan lain sebagainya dari proses awal sampai Berita Acara Serah Terima (BAST)"},
        {"kode_klasifikasi":"RT.00.06","uraian_informasi":"Tanah dan Bangunan"},
        {"kode_klasifikasi":"RT.00.06","uraian_informasi":"Penggunaan tanah dan bangunan kantor dan rumah dinas"},
        {"kode_klasifikasi":"RT.00.07","uraian_informasi":"Pakaian Dinas"},
        {"kode_klasifikasi":"RT.00.07","uraian_informasi":"Administrasi pakaian dinas pegawai, satpam, dan pegawai lainnya"},
        {"kode_klasifikasi":"RT.01","uraian_informasi":"Pemeliharaan"},
        {"kode_klasifikasi":"RT.01","uraian_informasi":"Pemeliharaan dan perawatan barang milik negara meliputi kegiatan pelaporan kerusakan, perawatan\/perbaikan bangunan\/gedung kantor, perawatan inventaris kantor, pemeliharaan alat telekomunikasi dan server\/hosting, perbaikan\/service kendaraan dinas serta perawatan dan kebersihan taman lingkungan kantor dan pemeliharaan lainnya meliputi pemeliharaan jaringan listrik, air, telepon, komputer, pemeliharaan fisik arsip berupa suhu, kelembaban, pelindungan terhadap kebakaran, banjir, fumigasi, dan lain-lain."},
        {"kode_klasifikasi":"RT.02","uraian_informasi":"Ketertiban dan Keamanan"},
        {"kode_klasifikasi":"RT.02.01","uraian_informasi":"Pengamanan, penjagaan dan pengawalan"},
        {"kode_klasifikasi":"RT.02.01","uraian_informasi":"Pengamanan lingkungan kantor seperti daftar piket satpam\/security, buku\/formulir tamu, pengaturan akses masuk lingkungan kantor BPK dan pengaturan perparkiran termasuk kartu parkir, penjagaan dan pengawalan terhadap pejabat, kantor, dan rumah dinas"},
        {"kode_klasifikasi":"RT.02.02","uraian_informasi":"Laporan ketertiban dan keamanan (kehilangan, kerusakan, kecelakaan, gangguan)"},
        {"kode_klasifikasi":"RT.03","uraian_informasi":"Administrasi Pengelolaan Parkir"},
        {"kode_klasifikasi":"HU.00","uraian_informasi":"Manajemen Isu dan Krisis (MIK)"},
        {"kode_klasifikasi":"HU.00.01","uraian_informasi":"Kliping Koran"},
        {"kode_klasifikasi":"HU.00.01","uraian_informasi":"Kliping Koran (menggunakan media berbasis web)"},
        {"kode_klasifikasi":"HU.00.02","uraian_informasi":"Daily News Monitoring (DNM)"},
        {"kode_klasifikasi":"HU.00.03","uraian_informasi":"Analisa Pemberitaan Media Cetak"},
        {"kode_klasifikasi":"HU.01","uraian_informasi":"Pengumpulan, Pengolahan dan Penyajian Informasi Kelembagaan"},
        {"kode_klasifikasi":"HU.01.01","uraian_informasi":"Majalah Warta BPK"},
        {"kode_klasifikasi":"HU.01.02","uraian_informasi":"Buletin Info BPK"},
        {"kode_klasifikasi":"HU.01.03","uraian_informasi":"Buku-Buku Mengenai Kelembagaan"},
        {"kode_klasifikasi":"HU.01.04","uraian_informasi":"Leaflet\/Sticker \/Brosur\/Poster\/Plakat tentang BPK"},
        {"kode_klasifikasi":"HU.01.05","uraian_informasi":"Buku Profil Anggota BPK"},
        {"kode_klasifikasi":"HU.02","uraian_informasi":"Public Awareness Campaign (PAC)"},
        {"kode_klasifikasi":"HU.02.01","uraian_informasi":"Publikasi Melalui Media Cetak dan Elektronik"},
        {"kode_klasifikasi":"HU.02.01","uraian_informasi":"Bukti Siar Kegiatan Advetorial\/Talk Show\/Live Report"},
        {"kode_klasifikasi":"HU.02.02","uraian_informasi":"Pengumuman\/Pemberitaan di Siska dan Website BPK"},
        {"kode_klasifikasi":"HU.02.02","uraian_informasi":"Pengumuman\/Pemberitaan untuk dipublikasikan di Siska dan Website BPK\/Media Sosial"},
        {"kode_klasifikasi":"HU.02.03","uraian_informasi":"Rekapitulasi Informasi yang Dipublikasikan Melalui Digital Signage"},
        {"kode_klasifikasi":"HU.02.03","uraian_informasi":"Rekapitulasi Informasi yang Dipublikasikan Melalui Digital Signage"},
        {"kode_klasifikasi":"HU.03","uraian_informasi":"Pengelolaan Informasi Publik"},
        {"kode_klasifikasi":"HU.03.01","uraian_informasi":"Permintaan Informasi Publik"},
        {"kode_klasifikasi":"HU.03.01","uraian_informasi":"Permintaan Informasi Publik meliputi Formulir Permintaan Informasi, Surat dari Peminta Informasi, Salinan Identitas Peminta Informasi"},
        {"kode_klasifikasi":"HU.03.02","uraian_informasi":"Pengaduan Masyarakat"},
        {"kode_klasifikasi":"HU.03.02","uraian_informasi":"Pengaduan Masyarakat meliputi Formulir Pengaduan Masyarakat (melalui e-ppid.go.id dan aplikasi siPadu), Surat Pengaduan dari Masyarakat, Foto dan Bukti Pendukung Pengaduan"},
        {"kode_klasifikasi":"HU.04","uraian_informasi":"Hubungan dengan Media Massa"},
        {"kode_klasifikasi":"HU.04.01","uraian_informasi":"Konferensi Pers\/Siaran Pers\/Press Release"},
        {"kode_klasifikasi":"HU.04.02","uraian_informasi":"Permohonan Kunjungan Wartawan dan Wawancara"},
        {"kode_klasifikasi":"HU.04.03","uraian_informasi":"Media Visit\/Media Gathering"},
        {"kode_klasifikasi":"HU.05","uraian_informasi":"Hubungan Antar Lembaga Pemerintah dan Non Pemerintah"},
        {"kode_klasifikasi":"HU.05.01","uraian_informasi":"Rapat Dengar Pendapat dengan DPR dan Rapat Konsultasi atau Kunjungan Kerja dengan Lembaga Perwakilan"},
        {"kode_klasifikasi":"HU.05.02","uraian_informasi":"Pelaksanaan Kegiatan Hubungan dan Kerjasama dengan Lembaga Non Pemerintah"},
        {"kode_klasifikasi":"HU.06","uraian_informasi":"Hubungan dengan Lembaga-Lembaga Pemeriksa di Luar Negeri"},
        {"kode_klasifikasi":"HU.06","uraian_informasi":"Korespondensi Terkait Kegiatan BPK dengan Lembaga Pemeriksa di Luar Negeri"},
        {"kode_klasifikasi":"HU.07","uraian_informasi":"Hubungan dengan INTOSAI, ASOSAI dan ASEANSAI dan Organisasi Internasional lainnya"},
        {"kode_klasifikasi":"HU.07.01","uraian_informasi":"Korespondensi terkait Kegiatan BPK dengan Organisasi Internasional"},
        {"kode_klasifikasi":"HU.07.01","uraian_informasi":"Korespondensi, perjalanan dinas pimpinan selama tahun berjalan terkait kegiatan BPK dengan Organisasi Internasional"},
        {"kode_klasifikasi":"HU.07.02","uraian_informasi":"Pelaksanaan Kegiatan INTOSAI, ASOSAI dan ASEANSAI dan Organisasi Internasional"},
        {"kode_klasifikasi":"HU.08","uraian_informasi":"Publikasi ke-BPK-an"},
        {"kode_klasifikasi":"HU.08.01","uraian_informasi":"Liputan Kegiatan Dinas Pimpinan, Acara Kedinasan dan Peristiwa-Peristiwa Bidang Masing-Masing Dalam Berbagai Media (Rekaman Suara\/Gambar\/Foto)"},
        {"kode_klasifikasi":"HU.08.02","uraian_informasi":"Pameran\/Lomba"},
        {"kode_klasifikasi":"HU.08.03","uraian_informasi":"Ucapan Terima Kasih, Form Pengumuman Belasungkawa, pemberian kenang-kenangan berupa plakat"},
        {"kode_klasifikasi":"KK.00","uraian_informasi":"Keprotokolan"},
        {"kode_klasifikasi":"KK.00.01","uraian_informasi":"Laporan Kegiatan Penyelenggaraan Acara Kedinasan"},
        {"kode_klasifikasi":"KK.00.01","uraian_informasi":"Upacara, Pelantikan, Peresmian dan Jamuan Termasuk Acara Peringatan Hari-Hari Besar"},
        {"kode_klasifikasi":"KK.00.02","uraian_informasi":"Kunjungan dinas dan luar negeri"},
        {"kode_klasifikasi":"KK.00.02","uraian_informasi":"Kunjungan dinas dalam dan luar negeri, kunjungan dinas pejabat lain\/pegawai"},
        {"kode_klasifikasi":"KK.01","uraian_informasi":"Kesekretariatan"},
        {"kode_klasifikasi":"KK.01.01","uraian_informasi":"Sidang BPK"},
        {"kode_klasifikasi":"KK.01.01","uraian_informasi":"Hasil Sidang Badan BPK meliputi Transkrip, Kesepakatan, Resume, Tindak Lanjut Hasil Sidang, Rekaman Audio dan Video, serta Segala Bentuk Hasil Sidang BPK selain yang termasuk Hasil Sidang BPK baik Hardcopy maupun Softcopy"},
        {"kode_klasifikasi":"KK.01.02","uraian_informasi":"Sidang BPK Lainnya"},
        {"kode_klasifikasi":"KK.01.02","uraian_informasi":"Undangan Daftar Hadir, Lembar Konfirmasi dan Segala Dokumen Sidang BPK selain yang termasuk Dokumen Hasil Sidang BPK"},
        {"kode_klasifikasi":"KK.01.03","uraian_informasi":"Hasil Rapat yang Dihadiri Badan"},
        {"kode_klasifikasi":"KK.01.03","uraian_informasi":"Hasil rapat yang dihadiri Badan meliputi Dokumen Hasil Rapat yang Dihadiri Badan seperti Resume, Rekaman Audio dan Video, serta Segala Bentuk Hasil Rapat yang Dihadiri Badan baik Hardcopy maupun Softcopy"},
        {"kode_klasifikasi":"KK.01.04","uraian_informasi":"Rapat yang Dihadiri Badan Lainnya"},
        {"kode_klasifikasi":"KK.01.04","uraian_informasi":"Dokumen Rapat yang Dihadiri Badan Lainnya seperti Undangan, Daftar Hadir, Lembar Konfirmasi, dan Segala Dokumen Rapat selain Rapat yang Dihadiri Badan"},
        {"kode_klasifikasi":"KK.01.05","uraian_informasi":"Sambutan, Pidato, Materi Kuliah"},
        {"kode_klasifikasi":"KK.01.06","uraian_informasi":"Agenda kegiatan pimpinan lembaga"},
        {"kode_klasifikasi":"KK.01.07","uraian_informasi":"Buku Tamu\/Daftar Hadir Kegiatan Badan"},
        {"kode_klasifikasi":"KK.01.08","uraian_informasi":"Daftar Nama\/Alamat"},
        {"kode_klasifikasi":"KK.01.08","uraian_informasi":"Daftar Nama\/Alamat Kantor Pejabat, Daftar Nama\/Alamat Badan dan Mantan Badan serta Eselon I dan Mantan Pejabat Eselon I"},
        {"kode_klasifikasi":"KK.01.09","uraian_informasi":"Memori Serah Terima Jabatan"},
        {"kode_klasifikasi":"KK.01.09","uraian_informasi":"Dokumen Memori Serah Terima Jabatan"},
        {"kode_klasifikasi":"KK.01.10","uraian_informasi":"Konsinyering"},
        {"kode_klasifikasi":"PW.00","uraian_informasi":"Kegiatan Pengawasan, Reviu, Penelitian, Pemantauan dan Evaluasi"},
        {"kode_klasifikasi":"PW.00.01","uraian_informasi":"Kebijakan Bidang Pengawasan\/Pemeriksaan Intern"},
        {"kode_klasifikasi":"PW.00.02","uraian_informasi":"Rencana Strategis Bidang Pengawasan\/ Pemeriksaan Intern"},
        {"kode_klasifikasi":"PW.00.03","uraian_informasi":"Rencana Tahunan\/Semesteran Kegiatan Pemeriksaan\/Reviu\/ Penelitian\/Pemantauan dan Evaluasi"},
        {"kode_klasifikasi":"PW.00.04","uraian_informasi":"Program Pengawasan \/Reviu\/Penelitian\/Pemantauan\/ Evaluasi"},
        {"kode_klasifikasi":"PW.00.05","uraian_informasi":"Temuan"},
        {"kode_klasifikasi":"PW.00.05","uraian_informasi":"Temuan Pemeriksaan (TP), Temuan Reviu (TR), Hasil Penelitian, Hasil Pemantauan, Hasil Evaluasi"},
        {"kode_klasifikasi":"PW.00.06","uraian_informasi":"Kertas Kerja"},
        {"kode_klasifikasi":"PW.00.06","uraian_informasi":"Kertas Kerja Pengawasan, Kertas Kerja Reviu, Kertas Kerja Penelitian, Kertas Kerja Pemantauan, Kertas Kerja Evaluasi, Kertas Kerja Penilaian Kualitas LHP, Kertas Kerja Pembangunan Zona Integritas, Kertas Kerja LAK, Kertas Kerja PMPRB, Kertas Kerja TPKN dan Laporan TPKN BPK, Kertas Kerja Penyusunan POS\/Juknis, Kertas Kerja Konsultasi"},
        {"kode_klasifikasi":"PW.01","uraian_informasi":"Laporan Hasil Pengawasan atas Pemeriksaan"},
        {"kode_klasifikasi":"PW.01.01","uraian_informasi":"Laporan Hasil Reviu"},
        {"kode_klasifikasi":"PW.01.01","uraian_informasi":"Laporan Hasil Reviu SPM Kinerja Pemeriksaan, Laporan Hasil Reviu atas Laporan Keuangan BPK\/RKA BPK\/RK BMN BPK, Laporan Hasil Reviu Pemberian Kompensasi atas Hasil Pemeriksaan berdasarkan Hasil Reviu Itama, Laporan Hasil Reviu atas Sistem Pemerolehan Keyakinan Mutu (SPKM) Kelembagaan, Laporan Konsolidasi Hasil Reviu SPM, Laporan Hasil Pengawasan Pemeriksaan Internal"},
        {"kode_klasifikasi":"PW.01.02","uraian_informasi":"Laporan Hasil Peer Review dan Pemantauan Tindak Lanjut (TL) atas Hasil Peer Review"},
        {"kode_klasifikasi":"PW.01.03","uraian_informasi":"Dokumentasi Sidang Majelis Kehormatan Kode Etik (MKKE)"},
        {"kode_klasifikasi":"PW.01.03","uraian_informasi":"Notulen sidang, SK Sidang MKKE, Berita Acara Pemeriksaan, dan lain-lain)"},
        {"kode_klasifikasi":"PW.01.04","uraian_informasi":"Laporan Penilaian Mandiri Pelaksanaan Reformasi Birokrasi (PMPRB)"},
        {"kode_klasifikasi":"PW.02","uraian_informasi":"Laporan Hasil Penilaian"},
        {"kode_klasifikasi":"PW.02.01","uraian_informasi":"Laporan Hasil Penilaian Penegakan Integritas (Pemberkasan dan Penelitian\/ Telaahan atas Dugaan Pelanggaran Disiplin\/Kode Etik)"},
        {"kode_klasifikasi":"PW.02.02","uraian_informasi":"Laporan Hasil Penilaian dalam Rangka Pemberian Penghargaan Satya Lencana Karya Satya\/Satya Lencana Wira Karya, dan penghargaan Lainnya"},
        {"kode_klasifikasi":"PW.02.03","uraian_informasi":"Laporan Hasil Penilaian\/Telaahan\/Kajian tentang dugaan pelanggaran disiplin dan pengaduan pegawai dan masyarakat"},
        {"kode_klasifikasi":"PW.02.04","uraian_informasi":"Bahan Sidang Ankum"},
        {"kode_klasifikasi":"PW.02.05","uraian_informasi":"Laporan Asistensi\/Reviu Konsep SK Hukuman Disiplin"},
        {"kode_klasifikasi":"PW.02.06","uraian_informasi":"Risalah Sidang Ankum"},
        {"kode_klasifikasi":"PW.02.07","uraian_informasi":"Penetapan Hukuman Disiplin"},
        {"kode_klasifikasi":"PW.02.08","uraian_informasi":"Administrasi Hukuman Disiplin"},
        {"kode_klasifikasi":"PW.03","uraian_informasi":"Laporan Hasil Pemantauan"},
        {"kode_klasifikasi":"PW.03.01","uraian_informasi":"Laporan Hasil Pemantauan TL atas Hasil Pemeriksaan Internal\/Reviu Itama"},
        {"kode_klasifikasi":"PW.03.02","uraian_informasi":"Laporan Pemantauan TL atas Reviu Sistem Pemerolehan Keyakinan Mutu (SPKM) Kelembagaan"},
        {"kode_klasifikasi":"PW.03.03","uraian_informasi":"Laporan Hasil penilaian Kualitas LHP dalam rangka pemberian penghargaan\/ reward"},
        {"kode_klasifikasi":"PW.04","uraian_informasi":"Laporan Hasil Evaluasi"},
        {"kode_klasifikasi":"PW.04.01","uraian_informasi":"Laporan Hasil Pengawasan Semesteran, Tahunan (Evaluasi)"},
        {"kode_klasifikasi":"PW.04.02","uraian_informasi":"Laporan Hasil Evaluasi atas hal-hal tertentu"},
        {"kode_klasifikasi":"PW.04.03","uraian_informasi":"Laporan Monitoring dan Evaluasi LHKASN (Laporan Hasil Kekayaan Aparatur Sipil Negara) dan LHKPN (Laporan Hasil Kekayaan Penyelenggara Negara)"},
        {"kode_klasifikasi":"PW.05","uraian_informasi":"Catatan Hasil Reviu (CHR) dan Ikhtisar Hasil Reviu (IHR)"},
        {"kode_klasifikasi":"PW.05.01","uraian_informasi":"Catatan Hasil Reviu (CHR)"},
        {"kode_klasifikasi":"PW.05.02","uraian_informasi":"Ikhtisar Hasil Reviu (IHR)"},
        {"kode_klasifikasi":"PW.06","uraian_informasi":"Dokumen Tindak Lanjut atas hasil reviu Sistem Pengendalian Mutu (SPM) Kelembagaan\/pemeriksaan internal\/Reviu PKPM"},
        {"kode_klasifikasi":"PW.07","uraian_informasi":"Laporan Berkala"},
        {"kode_klasifikasi":"PW.07.01","uraian_informasi":"Laporan Mingguan"},
        {"kode_klasifikasi":"PW.07.02","uraian_informasi":"Laporan Dua Mingguan"},
        {"kode_klasifikasi":"PW.07.03","uraian_informasi":"Laporan Bulanan, Laporan Triwulan"},
        {"kode_klasifikasi":"PW.07.04","uraian_informasi":"Laporan Semesteran"},
        {"kode_klasifikasi":"PW.07.05","uraian_informasi":"Laporan Tahunan Unit Kerja"},
        {"kode_klasifikasi":"PW.07.06","uraian_informasi":"Laporan Tahunan BPK"},
        {"kode_klasifikasi":"PW.07.07","uraian_informasi":"Laporan Kegiatan Khusus (Rapat Koordinasi Pengawasan)"},
        {"kode_klasifikasi":"PW.07.08","uraian_informasi":"Laporan Kegiatan Khusus (Manajemen Kinerja dan Manajemen Presensi)"},
        {"kode_klasifikasi":"PW.08","uraian_informasi":"Laporan Akuntabilitas Kinerja (LAK)"},
        {"kode_klasifikasi":"PW.09","uraian_informasi":"Laporan Evaluasi atas Kegiatan Pengawasan Itama"},
        {"kode_klasifikasi":"PW.10","uraian_informasi":"Laporan yang Diterima oleh Itama"},
        {"kode_klasifikasi":"PW.10.01","uraian_informasi":"Laporan Bulanan Satker"},
        {"kode_klasifikasi":"PW.10.02","uraian_informasi":"Laporan KAP"},
        {"kode_klasifikasi":"PW.10.03","uraian_informasi":"LHP Satker Auditorat\/Perwakilan"},
        {"kode_klasifikasi":"PW.10.04","uraian_informasi":"Laporan\/Pengaduan terkait Pelanggaran Kode Etik"},
        {"kode_klasifikasi":"PW.10.05","uraian_informasi":"Laporan Pengaduan Pelanggaran Disiplin ASN"},
        {"kode_klasifikasi":"PW.10.06","uraian_informasi":"Surat Tugas Pemeriksaan dari Satker"},
        {"kode_klasifikasi":"PW.11","uraian_informasi":"Dokumen Realisasi Anggaran yang Diterima dari Sekretariat Jenderal (Setjen)"},
        {"kode_klasifikasi":"PW.12","uraian_informasi":"Pertanggungjawaban Keuangan Negara"},
        {"kode_klasifikasi":"PW.12.01","uraian_informasi":"Laporan Hasil Pemeriksaan (LHP) Badan Pemeriksa Keuangan Republik Indonesia atas Laporan Keuangan"},
        {"kode_klasifikasi":"PW.12.02","uraian_informasi":"Hasil Pengawasan dan Pemeriksaan Internal"},
        {"kode_klasifikasi":"PW.12.03","uraian_informasi":"Laporan Aparat Pemeriksa Fungsional"},
        {"kode_klasifikasi":"PW.12.03","uraian_informasi":"Laporan Aparat Pemeriksa Fungsional meliputi LHP (Laporan Hasil Pemeriksaan), Memorandum Hasil Pemeriksaan (MHP), Tindak Lanjut\/Tanggapan LHP"},
        {"kode_klasifikasi":"PW.12.04","uraian_informasi":"Dokumen Penyelesaian Kerugian Negara (Tuntutan Perbendaharaan, Tuntutan Ganti Rugi)"},
        {"kode_klasifikasi":"PW.13","uraian_informasi":"Manajemen Risiko"},
        {"kode_klasifikasi":"PW.13.01","uraian_informasi":"Penilaian Risiko"},
        {"kode_klasifikasi":"PW.13.02","uraian_informasi":"Pengembangan Strategi dan Mitigasi Risiko"},
        {"kode_klasifikasi":"PW.13.02","uraian_informasi":"Pengembangan Strategi dan Mitigasi Risiko dengan menggunakan pemberdayaan Pengelolaan Sumber Daya"},
        {"kode_klasifikasi":"PW.14","uraian_informasi":"Pengawasan Kearsipan"},
        {"kode_klasifikasi":"PW.14.01","uraian_informasi":"Kegiatan Pengawasan, Reviu, Penelitian, Pemantauan dan Evaluasi Kearsipan"},
        {"kode_klasifikasi":"PW.14.01","uraian_informasi":"Kebijakan, Renstra Pengawasan, Program dan prosedur pengawasan kearsipan mulai dari perencanaan, pelaksanaan, pelaporan, Temuan Pengawasan Kearsipan dan Kertas Kerja Kearsipan, Reviu, Monitoring dan Evaluasi"},
        {"kode_klasifikasi":"PW.14.02","uraian_informasi":"Perencanaan Program Pengawasan"},
        {"kode_klasifikasi":"PW.14.02","uraian_informasi":"Jadwal Waktu, Obyek Pengawasan, Prioritas, Anggaran, Jenis dan Metode Pengawasan, Langkah Kerja"},
        {"kode_klasifikasi":"PW.14.03","uraian_informasi":"Pelaksanaan Pengawasan Kearsipan Internal"},
        {"kode_klasifikasi":"PW.14.03","uraian_informasi":"Pelaksanaan Pengawasan Kearsipan Internal meliputi penciptaan arsip, penggunaan arsip, pemeliharaan arsip dan penyusutan arsip, sumber daya manusia Unit Pengolah, sarana dan prasarana Unit Pengolah, dan lain-lain"},
        {"kode_klasifikasi":"PW.15","uraian_informasi":"Laporan Hasil Pengawasan Kearsipan"},
        {"kode_klasifikasi":"PW.15.01","uraian_informasi":"Laporan Audit Kearsipan Internal (LAKI)"},
        {"kode_klasifikasi":"PW.15.02","uraian_informasi":"Laporan Audit Kearsipan Internal (LAKI) Konsolidasi"},
        {"kode_klasifikasi":"PW.15.02","uraian_informasi":"LAKI Konsolidasi untuk diserahkan ke ANRI"},
        {"kode_klasifikasi":"PW.15.03","uraian_informasi":"Laporan Hasil Monitoring Tindak Lanjut (LHM)"},
        {"kode_klasifikasi":"PW.16","uraian_informasi":"Laporan Hasil Pengawasan ANRI"},
        {"kode_klasifikasi":"PW.16","uraian_informasi":"Laporan Audit Kearsipan Eksternal (LAKE)"},
        {"kode_klasifikasi":"PW.17","uraian_informasi":"Sanksi"},
        {"kode_klasifikasi":"PW.17.01","uraian_informasi":"Sanksi Administrasi"},
        {"kode_klasifikasi":"PW.17.01","uraian_informasi":"Rekomendasi pemberian sanksi administrasi terhadap pelanggaran atas ketentuan peraturan perundang-undangan kearsipan yang berlaku."},
        {"kode_klasifikasi":"PW.17.02","uraian_informasi":"Sanksi Pidana"},
        {"kode_klasifikasi":"PW.17.02","uraian_informasi":"Rekomendasi pemberian sanksi administrasi terhadap pelanggaran atas ketentuan peraturan perundang-undangan kearsipan yang berlaku."},
        {"kode_klasifikasi":"EP.00","uraian_informasi":"Bahan Penyusunan Ikhtisar Hasil Pemeriksaan Semesteran (IHPS)"},
        {"kode_klasifikasi":"EP.00","uraian_informasi":"SIHPS, DRHP, Hasil Evaluasi LHP, Matriks TP, Matriks TL, dan data pendukung lainnya"},
        {"kode_klasifikasi":"EP.01","uraian_informasi":"Laporan Hasil Evaluasi, Validasi Bahan Penyusunan IHPS, dan LHP dari Seluruh Satker"},
        {"kode_klasifikasi":"EP.02","uraian_informasi":"Konsep IHPS Koreksi dari Pimpinan"},
        {"kode_klasifikasi":"EP.03","uraian_informasi":"Konsep IHPS Koreksi dari Pimpinan Final yang Disetujui Pimpinan BPK"},
        {"kode_klasifikasi":"EP.04","uraian_informasi":"IHPS dan Surat Keluar"},
        {"kode_klasifikasi":"EP.05","uraian_informasi":"Administrasi Penyusunan Pendapat BPK"},
        {"kode_klasifikasi":"EP.05","uraian_informasi":"Penyusunan Pendapat BPK TOR\/Proposal, Pembentukan Tim Kerja, Surat Menyurat, Surat Permintaan Pendapat dan sebagainya"},
        {"kode_klasifikasi":"EP.06","uraian_informasi":"Bahan Penyusunan Pendapat BPK"},
        {"kode_klasifikasi":"EP.06.01","uraian_informasi":"Hasil Evaluasi atas LHP"},
        {"kode_klasifikasi":"EP.06.02","uraian_informasi":"Data-Data Pendukung Terkait Pemeriksaan, Tindak Lanjut Hasil Pemeriksaan, Hasil Evaluasi Pemeriksaan oleh KAP dan data lainnya"},
        {"kode_klasifikasi":"EP.06.03","uraian_informasi":"Pertimbangan\/Masukan\/Tanggapan dari Pihak Internal"},
        {"kode_klasifikasi":"EP.06.04","uraian_informasi":"Pertimbangan\/Masukan\/Tanggapan dari Pihak Eksternal"},
        {"kode_klasifikasi":"EP.06.05","uraian_informasi":"Usulan Bahan Pendapat dari AKN"},
        {"kode_klasifikasi":"EP.07","uraian_informasi":"Pendapat BPK dan Surat Keluar Penyerahan Pendapat BPK beserta pendukungnya atas Tindak Lanjut Pendapat BPK"},
        {"kode_klasifikasi":"EP.08","uraian_informasi":"Dokumen Pendaftaran KAP Untuk Menjadi KAP Terdaftar di BPK"},
        {"kode_klasifikasi":"EP.09","uraian_informasi":"Database\/Daftar KAP Terdaftar di BPK beserta dokumen pendukungnya"},
        {"kode_klasifikasi":"EP.10","uraian_informasi":"Surat Tanda Terdaftar KAP di BPK"},
        {"kode_klasifikasi":"EP.11","uraian_informasi":"Dokumen-Dokumen Terkait Tindak Lanjut dan Kerugian Negara\/Daerah"},
        {"kode_klasifikasi":"EP.12","uraian_informasi":"Penyusunan Rencana Kerja Pemeriksaan (RKP)"},
        {"kode_klasifikasi":"EP.12.01","uraian_informasi":"Kebijakan Bidang Pemeriksaan Atas Pengelolaan dan Tanggung jawab Keuangan Negara yang dilakukan oleh Pempus, Pemda, Lembaga Negara lainnya, BI, BUMN, BLU, BUMD, dan lembaga atau Badan yang lain mengelola keuangan negara"},
        {"kode_klasifikasi":"EP.12.01","uraian_informasi":"Pengkajian dan pengusulan kebijakan, penyiapan kebijakan, perumusan kebijakan, masukan dan dukungan kebijakan, Laporan Berkala mengenai Realisasi RKP"},
        {"kode_klasifikasi":"EP.12.02","uraian_informasi":"Rencana Pemeriksaan (atas Laporan Keuangan, Kinerja, Tujuan Tertentu\/PDTT)"},
        {"kode_klasifikasi":"EP.12.02","uraian_informasi":"Rencana Strategis Pemeriksaan, Rencana Kerja Pemeriksaan Tahunan dan prognosa RKP Dua Tahun ke depan"},
        {"kode_klasifikasi":"TI.00","uraian_informasi":"Sistem Informasi (SI)"},
        {"kode_klasifikasi":"TI.00.01","uraian_informasi":"Surat"},
        {"kode_klasifikasi":"TI.00.01","uraian_informasi":"Surat Sistem Informasi (SI)"},
        {"kode_klasifikasi":"TI.00.02","uraian_informasi":"Bahan Penyusunan Sistem Informasi"},
        {"kode_klasifikasi":"TI.00.03","uraian_informasi":"Daftar Usulan Kebutuhan User"},
        {"kode_klasifikasi":"TI.00.04","uraian_informasi":"Konsep Desain Sistem Informasi"},
        {"kode_klasifikasi":"TI.00.05","uraian_informasi":"Laporan Kebutuhan User"},
        {"kode_klasifikasi":"TI.00.06","uraian_informasi":"Kode Sumber"},
        {"kode_klasifikasi":"TI.00.07","uraian_informasi":"Hasil Uji Coba"},
        {"kode_klasifikasi":"TI.00.08","uraian_informasi":"Hasil User Acceptance Testing (UAT)"},
        {"kode_klasifikasi":"TI.00.09","uraian_informasi":"Backup Basis Data"},
        {"kode_klasifikasi":"TI.00.10","uraian_informasi":"Laporan Sistem Informasi (SI)"},
        {"kode_klasifikasi":"TI.00.11","uraian_informasi":"Kontrak Pengembangan SI dengan Pihak Ketiga"},
        {"kode_klasifikasi":"TI.00.12","uraian_informasi":"Kamus Data"},
        {"kode_klasifikasi":"TI.01","uraian_informasi":"Arsitektur dan Implementasi Sistem"},
        {"kode_klasifikasi":"TI.01.01","uraian_informasi":"Sistem Informasi (SI), Sistem Informasi Manajemen Kinerja Satker, Sistem Manajemen Pemeriksaan dan lain-lain, Sistem Informasi Database Pendapat Hukum, Sistem Informasi Kantor Akuntan Publik, Sistem Informasi Pendapat BPK, Sistem Informasi Pertimbangan BPK, Manajemen Layanan TI, Pengembangan Sistem Pengadaan Secara Elektronik Barang Milik Negara (BMN), Sistem Informasi Kerugian Negara\/Daerah (Majelis Tuntutan Perbendaharaan), Sistem Informasi Sumber Daya Manusia (SISDM)\/Sistem Informasi Kepegawaian terdiri dari Pengembangan Sistem Informasi Kepegawaian dan Pengolahan Data dan Informasi Kepegawaian, Sistem Informasi Diklat"},
        {"kode_klasifikasi":"TI.01.02","uraian_informasi":"Sistem Aplikasi LK, Sistem Aplikasi Pemeriksaan Tindak Lanjut, Sistem Aplikasi Persuratan, Sistem Aplikasi Sipadu, Implementasi Pengelolaan Arsip Elektronik mulai dari persiapan, pelaksanaan, pelaporan dan evaluasi di Unit Pengolah dan Unit Kearsipan, Kliping BPK berbasis web"},
        {"kode_klasifikasi":"TI.01.03","uraian_informasi":"Infrastruktur"},
        {"kode_klasifikasi":"TI.01.04","uraian_informasi":"Datawarehouse"},
        {"kode_klasifikasi":"TI.02","uraian_informasi":"Perekaman dan Pemutakhiran Datat"},
        {"kode_klasifikasi":"TI.02.01","uraian_informasi":"Formulir Isian"},
        {"kode_klasifikasi":"TI.02.02","uraian_informasi":"Daftar Petugas Perekaman"},
        {"kode_klasifikasi":"TI.02.03","uraian_informasi":"Jadwal Pelaksanaan"},
        {"kode_klasifikasi":"TI.02.04","uraian_informasi":"Laporan Hasil Perekaman dan Pemuktahiran Data"},
        {"kode_klasifikasi":"TI.03","uraian_informasi":"Migrasi Sistem Aplikasi dan Pengembangan Arsip Digital"},
        {"kode_klasifikasi":"TI.03.01","uraian_informasi":"Migrasi"},
        {"kode_klasifikasi":"TI.03.01","uraian_informasi":"Perencanaan, pelaksanaan, pelaporan, Berita Acara Migrasi dan Daftar Sistem Aplikasi dan Data yang Dimigrasi"},
        {"kode_klasifikasi":"TI.03.02","uraian_informasi":"Pengembangan Arsip Digital"},
        {"kode_klasifikasi":"TI.04","uraian_informasi":"Dokumen Hosting"},
        {"kode_klasifikasi":"TI.04.01","uraian_informasi":"Formulir Permintaan Hosting"},
        {"kode_klasifikasi":"TI.04.02","uraian_informasi":"Laporan Hasil Uji Kelayakan"},
        {"kode_klasifikasi":"TI.04.03","uraian_informasi":"Laporan Pelaksanaan Hosting"},
        {"kode_klasifikasi":"TI.05","uraian_informasi":"Dokumen Layanan Back-up Data Digital"},
        {"kode_klasifikasi":"TI.06","uraian_informasi":"Service Catalogue, SLA"},
        {"kode_klasifikasi":"KE.00","uraian_informasi":"Deposit Bahan Pustaka"},
        {"kode_klasifikasi":"KE.01","uraian_informasi":"Pengolahan Bahan Pustaka"},
        {"kode_klasifikasi":"KE.01.01","uraian_informasi":"Buku Induk"},
        {"kode_klasifikasi":"KE.01.01","uraian_informasi":"Buku Induk Buku, Buku Induk Majalah, Buku Induk Bahan Bukan Buku Induk berupa Daftar Inventaris Kolkesi CD, DVD, Kaset"},
        {"kode_klasifikasi":"KE.01.02","uraian_informasi":"Buram Katalog"},
        {"kode_klasifikasi":"KE.01.03","uraian_informasi":"Daftar Penerimaan dan Pengiriman dari Pengolahan ke Sirkulasi"},
        {"kode_klasifikasi":"KE.01.03","uraian_informasi":"Daftar Penerimaan dan Pengiriman Buku, Majalah dari Pengolahan ke Sirkulasi, dan Daftar Penerimaan Bahan Pustaka\/Hibah"},
        {"kode_klasifikasi":"KE.02","uraian_informasi":"Pelayanan Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.01","uraian_informasi":"Bukti Peminjaman Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.02","uraian_informasi":"Data dan Statistik Peminjaman dan Pengembalian Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.03","uraian_informasi":"Data dan Statistik Pengunjung Perpustakaan"},
        {"kode_klasifikasi":"KE.02.03","uraian_informasi":"Naskah-naskah yang berkaitan dengan Data dan Statistik Pengunjung Perpustakaan"},
        {"kode_klasifikasi":"KE.02.04","uraian_informasi":"Surat Tagihan"},
        {"kode_klasifikasi":"KE.02.05","uraian_informasi":"Survey Kondisi Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.06","uraian_informasi":"Reprografi Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.07","uraian_informasi":"Daftar Layanan Sirkulasi Bahan Pustaka"},
        {"kode_klasifikasi":"KE.02.08","uraian_informasi":"Daftar Kartu Keanggotaan"},
        {"kode_klasifikasi":"KE.02.09","uraian_informasi":"Daftar Koleksi Buku Tiap Tahun (terbaru)"},
        {"kode_klasifikasi":"KE.02.10","uraian_informasi":"Kartu Proquest dan e-Library"},
        {"kode_klasifikasi":"KE.03","uraian_informasi":"Preservasi Bahan Pustaka"},
        {"kode_klasifikasi":"KE.03","uraian_informasi":"Daftar Alih Media Bahan Pustaka Tercetak"},
        {"kode_klasifikasi":"DL.00","uraian_informasi":"Kebijakan"},
        {"kode_klasifikasi":"DL.00","uraian_informasi":"Kebijakan Bidang Diklat, Pengkajian dan Pengusulan Kebijakan, Penyiapan Kebijakan, Perumusan Kebijakan, Masukan dan Dukungan Kebijakan, Rencana Aksi, Kebijakan Evaluasi Diklat dan lainnya."},
        {"kode_klasifikasi":"DL.01","uraian_informasi":"Perencanaan Pendidikan dan Pelatihan"},
        {"kode_klasifikasi":"DL.01.01","uraian_informasi":"Standar Kediklatan"},
        {"kode_klasifikasi":"DL.01.01","uraian_informasi":"Standar Pelaksanaan, Standar Penilaian"},
        {"kode_klasifikasi":"DL.01.02","uraian_informasi":"Sistem dan Metode"},
        {"kode_klasifikasi":"DL.01.02","uraian_informasi":"Penyusunan, penyempurnaan dan pengembangan sistem dan metode diklat"},
        {"kode_klasifikasi":"DL.01.03","uraian_informasi":"Kurikulum dan Silabus"},
        {"kode_klasifikasi":"DL.01.03","uraian_informasi":"Penyusunan, penyempurnaan dan pengembangan kurikulum dan silabus diklat"},
        {"kode_klasifikasi":"DL.01.04","uraian_informasi":"Bahan Ajar"},
        {"kode_klasifikasi":"DL.01.04","uraian_informasi":"Kegiatan penyusunan, penyempurnaan, dan pengembangan bahan ajar (modul\/slide diklat, video), studi kasus dan media pembelajarannya"},
        {"kode_klasifikasi":"DL.01.05","uraian_informasi":"Panduan Fasilitator (Buku Instruktur\/Mentor\/Coach)"},
        {"kode_klasifikasi":"DL.01.06","uraian_informasi":"Analisis Kebutuhan Diklat\/TNA"},
        {"kode_klasifikasi":"DL.01.07","uraian_informasi":"Pengembangan Program dan Pembinaan Diklat"},
        {"kode_klasifikasi":"DL.01.07","uraian_informasi":"Standarisasi, Sistem Informasi Diklat, Konsultasi, Advokasi, Asistensi Diklat, Program Diklat, Pengelolaan Diklat (Pembimbingan, Sertifikasi, Akreditasi) Teknologi Pembelajaran, dan lain-lain."},
        {"kode_klasifikasi":"DL.01.08","uraian_informasi":"Monitoring Agenda Kediklatan"},
        {"kode_klasifikasi":"DL.01.09","uraian_informasi":"Dokumen Diklat"},
        {"kode_klasifikasi":"DL.01.09","uraian_informasi":"Kalender Diklat, Jadwal Pengajaran Diklat, Daftar Pengampuhan Widyaiswara, Data Peserta Diklat dan Rencana Tahunan Diklat, Katalog Diklat, Data Base Pengajar dan Alumni Diklat, dan lain-lain"},
        {"kode_klasifikasi":"DL.02","uraian_informasi":"Penyelenggaraan Pendidikan dan Pelatihan"},
        {"kode_klasifikasi":"DL.02.01","uraian_informasi":"Diklat Orientasi Calon Pegawai Negeri Sipil (CPNS)"},
        {"kode_klasifikasi":"DL.02.01","uraian_informasi":"Diklat Orientasi CPNS mulai dari perencanaan\/persiapan, pelaksanaan, pelaporan"},
        {"kode_klasifikasi":"DL.02.02","uraian_informasi":"Diklat Fungsional Pemeriksa"},
        {"kode_klasifikasi":"DL.02.02","uraian_informasi":"Kegiatan kursus\/diklat fungsional mulai dari perencanaan\/persiapan, pelaksanaan, pelaporan"},
        {"kode_klasifikasi":"DL.02.03","uraian_informasi":"Diklat Teknis"},
        {"kode_klasifikasi":"DL.02.03","uraian_informasi":"Kegiatan kursus\/diklat teknis mulai dari perencanaan\/persiapan, pelaksanaan, pelaporan diklat teknis pemeriksa dan non pemeriksa"},
        {"kode_klasifikasi":"DL.02.04","uraian_informasi":"Diklat Pelatihan Penjenjangan Jabatan"},
        {"kode_klasifikasi":"DL.02.04","uraian_informasi":"Pelatihan penjenjangan mulai dari perencanaan\/persiapan, pelaksanaan, pelaporan diklat penjenjangan pegawai dari tingkat eselon I dan II\/Jabatan Pimpinan Tinggi sampai dengan tingkat eselon III dan IV\/Jabatan Administrasi"},
        {"kode_klasifikasi":"DL.02.05","uraian_informasi":"Sertifikasi Diklat\/Sertifikasi Sumber Daya Manusia Kediklatan"},
        {"kode_klasifikasi":"DL.02.05","uraian_informasi":"Kompetensi pegawai (sertifikasi SDM kediklatan, sertifikasi pengadaan barang dan jasa, sertifikasi kearsipan, dan lain-lain), petunjuk teknis sertifikasi, instrumen sertifikat, registrasi sertifikat\/STTPL peserta diklat, kertas kerja sertifikat, hasil sertifikasi, pemantauan pemegang sertifikat, piagam penghargaan dan lain-lain"},
        {"kode_klasifikasi":"DL.02.06","uraian_informasi":"Dokumen Saran\/Rekomendasi Penyelenggaraan Diklat"},
        {"kode_klasifikasi":"DL.03","uraian_informasi":"Evaluasi dan Pelaporan Pendidikan dan Pelatihan"},
        {"kode_klasifikasi":"DL.03.01","uraian_informasi":"Evaluasi Penyelenggaraan Diklat"},
        {"kode_klasifikasi":"DL.03.01","uraian_informasi":"Evaluasi penyelenggaraan diklat meliputi instrumen evaluasi, program evaluasi, kertas kerja evaluasi, laporan evaluasi, dan lain-lain"},
        {"kode_klasifikasi":"DL.03.02","uraian_informasi":"Evaluasi Pasca Diklat"},
        {"kode_klasifikasi":"DL.03.02","uraian_informasi":"Evaluasi setelah penyelenggaraan diklat meliputi laporan pemantauan hasil evaluasi diklat, laporan ikhtisar evaluasi, hasil evaluasi diklat level 1, dan 2"},
        {"kode_klasifikasi":"DL.04","uraian_informasi":"Bimbingan\/Konsultasi\/Pendampingan\/Supevisi\/Pembinaan\/Penyuluhan\/ Diseminasi untuk Peningkatan Kualitas Pegawai"},
        {"kode_klasifikasi":"DL.04.01","uraian_informasi":"Bimbingan\/Bimbingan Teknis"},
        {"kode_klasifikasi":"DL.04.02","uraian_informasi":"Konsultasi"},
        {"kode_klasifikasi":"DL.04.03","uraian_informasi":"Pendampingan"},
        {"kode_klasifikasi":"DL.04.04","uraian_informasi":"Supervisi"},
        {"kode_klasifikasi":"DL.04.04","uraian_informasi":"Supervisi atas Penelitian"},
        {"kode_klasifikasi":"DL.04.05","uraian_informasi":"Pembinaan"},
        {"kode_klasifikasi":"DL.04.06","uraian_informasi":"Penyuluhan"},
        {"kode_klasifikasi":"DL.04.07","uraian_informasi":"Diseminasi"},
        {"kode_klasifikasi":"DL.05","uraian_informasi":"Master Proceeding, Seminar, Lokakarya\/Temukarya\/Workshop, Sosialisasi, Kursus\/Shortcourse dan Ujian Profesi, Knowledge Transfer Forum (KTF), Focus Group Discussi"},
        {"kode_klasifikasi":"BM.00","uraian_informasi":"Kebijakan"},
        {"kode_klasifikasi":"BM.00.01","uraian_informasi":"Pengkajian dan pengusulan kebijakan"},
        {"kode_klasifikasi":"BM.00.02","uraian_informasi":"Penyiapan Kebijakan"},
        {"kode_klasifikasi":"BM.00.03","uraian_informasi":"Perumusan kebijakan"},
        {"kode_klasifikasi":"BM.00.04","uraian_informasi":"Penetapan kebijakan"},
        {"kode_klasifikasi":"BM.01","uraian_informasi":"Pelaksanaan Pengadaan"},
        {"kode_klasifikasi":"BM.01.01","uraian_informasi":"Penyusunan Rencana Umum Pengadaan"},
        {"kode_klasifikasi":"BM.01.01","uraian_informasi":"Identifikasi dan Analisis Kebutuhan Barang\/Jasa, Penyusunan dan Penetapan Rencana Penganggaran Pengadaan, Penetapan Kebijakan Umum, Penyusunan Kerangka Acuan Kerja (KAK), Pengumuman Rencana Umum Pengadaan"},
        {"kode_klasifikasi":"BM.01.02","uraian_informasi":"Pemilihan Penyedia"},
        {"kode_klasifikasi":"BM.01.02","uraian_informasi":"Persiapan Pemilihan Penyedia, dan Pelaksanaan Pemilihan Penyedia"},
        {"kode_klasifikasi":"BM.01.03","uraian_informasi":"Penandatanganan Kontrak dan Pelaksanaan Kontrak"},
        {"kode_klasifikasi":"BM.01.03","uraian_informasi":"Penandatanganan Kontrak dan Pelaksanaan Kontrak"},
        {"kode_klasifikasi":"BM.01.04","uraian_informasi":"Swakelola"},
        {"kode_klasifikasi":"BM.01.04","uraian_informasi":"Perencanaan, Pelaksanaan dan Pengawasan dan Evaluasi"},
        {"kode_klasifikasi":"BM.02","uraian_informasi":"Pengembangan Strategi Pengadaan"},
        {"kode_klasifikasi":"BM.02.01","uraian_informasi":"Pengembangan Strategi Pengadaan Umum"},
        {"kode_klasifikasi":"BM.02.01","uraian_informasi":"Barang dan Jasa, Pekerjaan Konstruksi."},
        {"kode_klasifikasi":"BM.02.02","uraian_informasi":"Pengembangan Strategi Pengadaan Khusus"},
        {"kode_klasifikasi":"BM.02.02","uraian_informasi":"Kemitraan Pemerintah dengan Badan Usaha Badan Usaha dan Keadaan Khusus"},
        {"kode_klasifikasi":"BM.03","uraian_informasi":"Monitoring dan Evaluasi Pengadaan"},
        {"kode_klasifikasi":"BM.03.01","uraian_informasi":"Perencanaan, Monitoring dan Evaluasi Pengadaan"},
        {"kode_klasifikasi":"BM.03.02","uraian_informasi":"Pengembangan Sistem Katalog"},
        {"kode_klasifikasi":"BM.03.02","uraian_informasi":"Riset dan Kontrak, Pengelolaan Katalog."},
        {"kode_klasifikasi":"BM.04","uraian_informasi":"Laporan Pengelolaan Barang Milik Negara (BMN)"},
        {"kode_klasifikasi":"PP.00","uraian_informasi":"Pemeriksaan atas Anggaran Pendapatan dan Belanja Negara (APBN)"},
        {"kode_klasifikasi":"PP.00.01","uraian_informasi":"Pemeriksaan Laporan Keuangan"},
        {"kode_klasifikasi":"PP.00.01","uraian_informasi":"Obyek pemeriksaan laporan keuangan dengan sumber pendanaaan APBN"},
        {"kode_klasifikasi":"PP.00.02","uraian_informasi":"Pemeriksaan Kinerja"},
        {"kode_klasifikasi":"PP.00.02","uraian_informasi":"Obyek pemeriksaan laporan kinerja dengan sumber pendanaaan APBN"},
        {"kode_klasifikasi":"PP.00.03","uraian_informasi":"Pemeriksaan Dengan Tujuan Tertentu"},
        {"kode_klasifikasi":"PP.00.03","uraian_informasi":"Obyek pemeriksaan dengan tujuan tertentu dengan sumber pendanaaan APBN"},
        {"kode_klasifikasi":"PP.01","uraian_informasi":"Pemeriksaan atas Badan Usaha Milik Negara (BUMN)"},
        {"kode_klasifikasi":"PP.01.01","uraian_informasi":"Pemeriksaan Laporan Keuangan"},
        {"kode_klasifikasi":"PP.01.01","uraian_informasi":"Obyek pemeriksaan laporan keuangan dengan sumber pendanaaan BUMN"},
        {"kode_klasifikasi":"PP.01.02","uraian_informasi":"Pemeriksaan Kinerja"},
        {"kode_klasifikasi":"PP.01.02","uraian_informasi":"Obyek pemeriksaan laporan kinerja dengan sumber pendanaaan BUMN"},
        {"kode_klasifikasi":"PP.01.03","uraian_informasi":"Pemeriksaan Dengan Tujuan Tertentu"},
        {"kode_klasifikasi":"PP.01.03","uraian_informasi":"Obyek pemeriksaan dengan tujuan tertentu dengan sumber pendanaaan BUMN"},
        {"kode_klasifikasi":"PP.02","uraian_informasi":"Pemeriksaan atas Anggaran Pendapatan Belanja Daerah (APBD)"},
        {"kode_klasifikasi":"PP.02.01","uraian_informasi":"Pemeriksaan Laporan Keuangan"},
        {"kode_klasifikasi":"PP.02.01","uraian_informasi":"Obyek pemeriksaan laporan keuangan dengan sumber pendanaaan APBD"},
        {"kode_klasifikasi":"PP.02.02","uraian_informasi":"Pemeriksaan Kinerja"},
        {"kode_klasifikasi":"PP.02.02","uraian_informasi":"Obyek pemeriksaan laporan kinerja dengan sumber pendanaaan APBD"},
        {"kode_klasifikasi":"PP.02.03","uraian_informasi":"Pemeriksaan Dengan Tujuan Tertentu"},
        {"kode_klasifikasi":"PP.02.03","uraian_informasi":"Obyek pemeriksaan dengan tujuan tertentu dengan sumber pendanaaan APBD"},
        {"kode_klasifikasi":"PP.03","uraian_informasi":"Pemeriksaan atas Badan Usaha Milik Daerah (BUMD)"},
        {"kode_klasifikasi":"PP.03.01","uraian_informasi":"Pemeriksaan Laporan Keuangan"},
        {"kode_klasifikasi":"PP.03.01","uraian_informasi":"Obyek pemeriksaan laporan keuangan dengan sumber pendanaaan BUMD"},
        {"kode_klasifikasi":"PP.03.02","uraian_informasi":"Pemeriksaan Kinerja"},
        {"kode_klasifikasi":"PP.03.02","uraian_informasi":"Obyek pemeriksaan laporan kinerja dengan sumber pendanaaan BUMD"},
        {"kode_klasifikasi":"PP.03.03","uraian_informasi":"Pemeriksaan Dengan Tujuan Tertentu"},
        {"kode_klasifikasi":"PP.03.03","uraian_informasi":"Obyek pemeriksaan dengan tujuan tertentu dengan sumber pendanaaan BUMD"},
        {"kode_klasifikasi":"PP.04","uraian_informasi":"Pemeriksaan atas Anggaran yang sumber pendanaannya lebih dari 1 (satu) anggaran"},
        {"kode_klasifikasi":"PP.04.01","uraian_informasi":"Pemeriksaan Laporan Keuangan"},
        {"kode_klasifikasi":"PP.04.01","uraian_informasi":"Obyek pemeriksaan laporan keuangan"},
        {"kode_klasifikasi":"PP.04.02","uraian_informasi":"Pemeriksaan Kinerja"},
        {"kode_klasifikasi":"PP.04.02","uraian_informasi":"Obyek pemeriksaan pemeriksaan kinerja"},
        {"kode_klasifikasi":"PP.04.03","uraian_informasi":"Pemeriksaan Dengan Tujuan Tertentu"},
        {"kode_klasifikasi":"PP.04.03","uraian_informasi":"Obyek pemeriksaan pemeriksaan dengan tujuan tertentu"},
        {"kode_klasifikasi":"PP.05","uraian_informasi":"Pemeriksaan Investigasi"},
        {"kode_klasifikasi":"PP.05.01","uraian_informasi":"Pemeriksaan atas Anggaran Pendapatan dan Belanja Negara (APBN), Pemeriksaan atas Anggaran Pendapatan dan Belanja Negara (BUMN), Pemeriksaan atas Anggaran Pendapatan dan Belanja Daerah (APBD), Pemeriksaan atas Anggaran Pendapatan dan Belanja Daerah (BUMD)"},
        {"kode_klasifikasi":"PP.05.02","uraian_informasi":"Perhitungan Kerugian Daerah"},
        {"kode_klasifikasi":"PP.05.03","uraian_informasi":"Pemberian Keterangan Ahli (PKA)"},
        {"kode_klasifikasi":"PP.06","uraian_informasi":"Pemantauan Tindak Lanjut Hasil Pemeriksaan dan penyelesaian Kerugian Negara"},
        {"kode_klasifikasi":"PP.06.01","uraian_informasi":"Pemantauan atas Tindak Lanjut Hasil Pemeriksaan"},
        {"kode_klasifikasi":"PP.06.02","uraian_informasi":"Pemantauan Penyelesaian Kerugian Negara\/Daerah"}
    ]

module.exports = {Option}